### ISSUE TITLE
Problem at Question Bank Contens

### ISSUE THREAD

**Issue by riegado** [academic-moodle-cooperation/moodle-mod_offlinequiz#1]
Hallo 
have tested the offlinequiz in moodle 2.7 and deteckted a problem.
The Question Bank Contens is not correctly displayed.
runns until ./editlib.php: print_qtype_to_add_option(question_bank::get_qtype('multichoice'));

found out, that the print_qtype_to_add_option() not exists any more.

Regards
Adolf Rieger

**Comment by kaspot** [comment]
Hi, 
in the newest 2.8 version the lang string for totalpointsx is already set to 'Total of marks: {$a}'.

**Comment by germanvaleroelizondo** [comment]
Thanks kaspot
