### ISSUE TITLE
scan Answer sheet not working

### ISSUE THREAD

**Issue by rratna** [academic-moodle-cooperation/moodle-mod_offlinequiz#10]
I am trying to scan a answer sheet and I am getting the list of errors on server as this code is part of batch job process.
offlinequiz\report\rimport\scanner.php
-------------------------------
global $CFG;

    //if ($x >= imagesx($this->image) or $x >= imagesy($this->image)) { // point is out of range

    if ($x > imagesx($this->image) or $x > imagesy($this->image)) { 
        return false; 
    }
    $rgb = imagecolorsforindex($this->image, imagecolorat($this->image, $x, $y));
    $gray = $rgb['red'] + $rgb['green'] + $rgb['blue'];

    if ($gray > $this->papergray) {
        return false;
    } else {
        return true;
    }
---------------------------------
the error is in line:
----------------------------------
$rgb = imagecolorsforindex($this->image, imagecolorat($this->image, $x, $y));
And error is:

Notice: imagecolorat(): 1520,-416 is out of bounds in C:\inetpub\wwwroot\elms\mo d\offlinequiz\report\rimport\scanner.php on line 1090

Notice: imagecolorat(): 1520,-415 is out of bounds in C:\inetpub\wwwroot\elms\mo d\offlinequiz\report\rimport\scanner.php on line 1090

Notice: imagecolorat(): 1520,-416 is out of bounds in C:\inetpub\wwwroot\elms\mo d\offlinequiz\report\rimport\scanner.php on line 1090

(Cont ....)
-----------------------------------
The initial check is not checking all conditions and is also wrong. When x,y are out of range the code should return false and not even try to call imagecolorat().

**Comment by juzi** [comment]
could you please send my your image file s.t. I can have a look at it?
If you have a suggestion on how to make the code better, please send it to me and I can integrate it in to the module.

**Comment by rratna** [comment]
![csu3](https://cloud.githubusercontent.com/assets/12519334/9882516/dd68baa6-5b89-11e5-84cc-9cd296b38634.jpg)

her is one answer sheet. Sorry Juzi... i am not the expert of php. the last words (The initial check is not checking all conditions and is also wrong. When x,y are out of range the code should return false and not even try to call imagecolorat(). ) are the suggestion from someone on my issue. 
Thanks! 
Every time error is related to either out of bounds or Trying to get property of non-object.
Every time i just getting some error while either uploading the answer sheet or running cron.php for result analysis.
Is there any one who is running this plugin successfully?

**Comment by juzi** [comment]
Sorry, but I only see  [Uploading csu3.jpg…]() in youir post. I don't know why I can't see the actual image.
