### ISSUE TITLE
 Exported PDF document display scramble code 

### ISSUE THREAD

**Issue by hffei** [academic-moodle-cooperation/moodle-mod_offlinequiz#100]
Hello

When I export the title PDF format, it shows scrambled code.
![image](https://user-images.githubusercontent.com/25144604/55304930-8971e280-5480-11e9-8f27-7ad386ee0062.png)

If I export the title in docx format, the display is correct.

How to deal with this problem?

**Comment by univietw** [comment]
Hi hffei,
This seems to be a problem with the pdf library we use. I can't do anything about it at the moment.
