### ISSUE TITLE
Temporary files are not deleted

### ISSUE THREAD

**Issue by jaume77** [academic-moodle-cooperation/moodle-mod_offlinequiz#106]
Hi,

From the tests we have done, it seems that temporary image files are never deleted.

The configuration variable "**keepfilesfordays**" does not work.

Depending on the volume of exams, and due to the size of each .tiff image, it can cause a space problem in the moodledata directory

Greetings and thanks!

**Comment by goggo24** [comment]
Thanks for reporting. We will fix it with v.3.7.0.

**Comment by jaume77** [comment]
Thanks Eva!

Do you have a forecast of when version 3.7 will be available in stable?

**Comment by univietw** [comment]
3.7 should become available within the next month. The only missing thing is the detailed test. The master branch has the fix to your problem already included.
