### ISSUE TITLE
utf8 support for question text

### ISSUE THREAD

**Issue by jdpark7** [academic-moodle-cooperation/moodle-mod_offlinequiz#107]
When the questions are converted into pdf file format for downloading, the question texts in unicode are not displayed correctly.
![encoding-error](https://user-images.githubusercontent.com/1614145/58370224-fc5a7f80-7f3e-11e9-8f47-24417765dad9.png)

**Comment by jdpark7** [comment]
I solved the problem by installing Korean fonts for tcpdf. Thanks.

**Comment by goggo24** [comment]
Great, that you found a solution.

**Comment by fishfree** [comment]
> installing Korean fonts for tcpdf

Could you share your solution in detail, please? I have the similar problem with Chinese.

**Comment by univietw** [comment]
I don't know how jdpark7 did it, but there is a manual on the moodle docs page:
https://docs.moodle.org/38/en/Add_fonts_for_embedding
No guarantee that it works with offlinequiz though.

**Comment by fishfree** [comment]
@univietw Thank you! I will try later.
