### ISSUE TITLE
offlinequiz_print_question_preview() in locallib.php break preformatted style

### ISSUE THREAD

**Issue by obook** [academic-moodle-cooperation/moodle-mod_offlinequiz#108]
Hello,
In locallib.php, in function offlinequiz_print_question_preview(), line #1562, this commands remove p tags AND pre tags. Is bad for questions with source code choice.

            // Remove all paragraph tags because they mess up the layout.
            $answertext = preg_replace("/<p[^>]*>/ms", "", $answertext);
            $answertext = preg_replace("/<\/p[^>]*>/ms", "", $answertext);

I suggest to change :

            // Remove all paragraph tags because they mess up the layout.
            $answertext = preg_replace( '/<p>(.+)<\/p>/Uuis', '$1', $answertext );

Thank for your advice.
Olivier.

**Comment by goggo24** [comment]
Bug fixed with v.3.9.0. - already published. Have fun!
