### ISSUE TITLE
bug : display: questionpage 1\n on createquiz.php , line #279

### ISSUE THREAD

**Issue by obook** [academic-moodle-cooperation/moodle-mod_offlinequiz#109]
Edit createquiz.php , line #279 : change \n to \<br\>

`print('questionpage '. $question->page . '\<br\>');`

Also you can comment this line because questionpage information is not very usefull.

Regards,
Olivier.

**Comment by goggo24** [comment]
Which version do you use? This bug should be already fixed with v.3.6.2+ - see
https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/77
