### ISSUE TITLE
offlinequiz/cron.php is not running

### ISSUE THREAD

**Issue by rratna** [academic-moodle-cooperation/moodle-mod_offlinequiz#11]
Every time the the cron is showing the following error.
----------------------------
No log handling enabled - turning on stderr logging
Cannot find module (IP-MIB): At line 0 in (none)
Cannot find module (IF-MIB): At line 0 in (none)
Cannot find module (TCP-MIB): At line 0 in (none)
Cannot find module (UDP-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-MIB): At line 0 in (none)
Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (SNMPv2-SMI): At line 0 in (none)
Cannot find module (NOTIFICATION-LOG-MIB): At line 0 in (none)
Cannot find module (UCD-SNMP-MIB): At line 0 in (none)
Cannot find module (UCD-DEMO-MIB): At line 0 in (none)
Cannot find module (SNMP-TARGET-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-AGENT-MIB): At line 0 in (none)
Cannot find module (DISMAN-EVENT-MIB): At line 0 in (none)
Cannot find module (SNMP-VIEW-BASED-ACM-MIB): At line 0 in (none)
Cannot find module (SNMP-COMMUNITY-MIB): At line 0 in (none)
Cannot find module (UCD-DLMOD-MIB): At line 0 in (none)
Cannot find module (SNMP-FRAMEWORK-MIB): At line 0 in (none)
Cannot find module (SNMP-MPD-MIB): At line 0 in (none)
Cannot find module (SNMP-USER-BASED-SM-MIB): At line 0 in (none)
Cannot find module (SNMP-NOTIFICATION-MIB): At line 0 in (none)
Cannot find module (SNMPv2-TM): At line 0 in (none)
--------------------------
what this is related to? Also on cron.php

the following if condition is not true any time so the function is not called any time.
-------------------------------------------
list($options, $unrecognized) = cli_get_params(array('cli' => false), array('h' => 'help'));

if (array_key_exists('cli', $options) && $options['cli']) 
{
    echo date('Y-m-d-H:i') . ': ';
    offlinequiz_evaluation_cron();
    echo " done.\n";
    die();
}
--------------------------------------------

**Comment by juzi** [comment]
You'll have to pass the --cli parameter to the cron.php as described in the Readme.txt 
https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/blob/master/README.txt

i.e. something like 
` */10 * * * * DATE=`date +\%Y\%m\%d`; php <your moodle root dir>/mod/offlinequiz/cron.php --cli=1`

**Comment by orion22** [comment]
I have
php /home/************/public_html/mod/offlinequiz/cron.php --cli=1 >> /home/*******/offlinequiz.txt 2>&1

and cron.php does not work properly because in the file offlinequiz.txt :
X-Powered-By: PHP/5.6.13
Content-type: text/html; charset=UTF-8

and nothing more
