### ISSUE TITLE
Error when Import scan pdf in quiz

### ISSUE THREAD

**Issue by Dataset1** [academic-moodle-cooperation/moodle-mod_offlinequiz#112]
![Screenshot_2019-09-11 Erreur](https://user-images.githubusercontent.com/55243568/64789388-8bce8180-d574-11e9-88c5-3554e0d60ae2.png)

When I do import the quiz scan pdf I have an error in table mdl_offlinequiz_page_corners.
The parameters x and y are NAN (not a number I suppose).
I suppose it's position of corners but I don't understand why it's not a value.
The error is picture type is not supported.
I try pdf and jpg but nothing is right

**Comment by univietw** [comment]
Hi, this seems to be a programming error. Would you be able to send me the PDF/JPEG and your exported offlinequiz instance?

**Comment by Dataset1** [comment]
[20190913091621511.pdf](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/files/3608828/20190913091621511.pdf)

I join the scan quiz pdf.

**Comment by univietw** [comment]
I will look into it and come back to you soon

**Comment by univietw** [comment]
So the problem is that you uploaded the participants forms together with the offlinequiz forms.
The offlinequiz forms should be uploaded on the "results->Upload/Correct" and the participantslist (the first 2 pages of your PDF) need to be uploaded at "participants->Upload/Correct". I hope this works. Greetings
Thomas

**Comment by Dataset1** [comment]
It works. thanks you.
But Now I have an other problem.
I have somes quiz ok but other I have 0% and no answer in Moodle.
When I import pdf, the program propose to correct alignment, check box manually.
The answers checked by the student in paper do not appear in the moodle form. As if he had not answered. => correction 0%
Check box on paper is ok, scan ocr is ok,  but import in moodle is not ok, he is empty with no answer.
I don't understand.

**Comment by Dataset1** [comment]
![20-09-2019 17-00-27](https://user-images.githubusercontent.com/55243568/65337427-67078900-dbc8-11e9-8a5c-a0307b70bb3b.jpg)

**Comment by Dataset1** [comment]
![20-09-2019 17-04-02](https://user-images.githubusercontent.com/55243568/65337633-d1202e00-dbc8-11e9-8f60-f2ad31f305a2.jpg)

**Comment by Dataset1** [comment]
![20-09-2019 17-05-52](https://user-images.githubusercontent.com/55243568/65337703-fb71eb80-dbc8-11e9-891f-539e91d3e6ec.jpg)

**Comment by Dataset1** [comment]
I see four green square to question 1,2,3,4 in the response scan.
The OCR take the squares that are not sided.

**Comment by goggo24** [comment]
@Dataset1 is offline test running in the meantime or do you still get errors?
