### ISSUE TITLE
Plugin not working with their respective version

### ISSUE THREAD

**Issue by caiadogithub** [academic-moodle-cooperation/moodle-mod_offlinequiz#116]
Hi,

The plugin, in version 3.4.2, worked perfectly when installed on Moodle version 3.4.

After upgrading to Moodle 3.5, I updated the plugin to version 3.5.4 and after this update the plugin has stopped working (it does not correctly recognize scanned pages).

In an another Moodle installation (development) I installed versions M3.6 and M3.7 with the plugin in their respective versions and could not make it work, as it has the same problems of not recognizing the scanned pages.

My current situation is as follows: I have Moodle version 3.5.2 with the plugin installed on version 3.4.2 working perfectly.

Any idea what might be going on?

Ricardo

**Comment by univietw** [comment]
What exactly isn't working? Do you get an error message while uploading? Or doesn't it find the boxes?

**Comment by caiadogithub** [comment]
After scanning the page and submitting it, the plugin does not recognize the boxes correctly.

Using the plugin in its version 3.4.2 in Moodle 3.5.2 works perfectly. However, when upgrading the plugin to version 3.5 the error appears.

**Comment by univietw** [comment]
does that happen with all Files? What file extension are you using?
Between 3.4 and 3.5 we changed a couple of things regarding file upload (ZIP-Files, multi-Tiff, black/white-converting) and the new experimental evaluation algorithm, which is not turned on by default.
Still, 3.4.2 seems safe to use with Moodle 3.5, starting with 3.7 though you will run into issues regarding pictures in PDF.

**Comment by caiadogithub** [comment]
Plugin 3.4.2 / Moodle 3.5
ZIP with PDF: Fail
ZIP with JPG: Pass

Plugin 3.5 / Moodle 3.5
ZIP with PDF: Fail
ZIP with JPG: Fail

Plugin 3.6 / Moodle 3.6
ZIP with PDF: Fail
ZIP with JPG: Fail

Plugin 3.7 / Moodle 3.7
ZIP with PDF: Fail
ZIP with JPG: Fail

![errooffquiz](https://user-images.githubusercontent.com/23316275/66334878-43ef1000-e910-11e9-8c19-bad9c12dc669.png)

**Comment by univietw** [comment]
It seems like you uploaded the sheets for the results in the participants list. you need to upload it at in the right tab "results"

**Comment by caiadogithub** [comment]
I upload the files using the "Results Tab".

![Participants_tab-Error](https://user-images.githubusercontent.com/23316275/66488039-b6343180-ea83-11e9-9332-146efd9692ab.png)
![Results_Tab-2_processing](https://user-images.githubusercontent.com/23316275/66488040-b6343180-ea83-11e9-829d-c19aafe2dc5b.png)
![Results_Tab-1_import](https://user-images.githubusercontent.com/23316275/66488041-b6343180-ea83-11e9-9c6e-db30aae8581a.png)
![Results_Tab-3-processing_error](https://user-images.githubusercontent.com/23316275/66488043-b6343180-ea83-11e9-944a-7aec76b82374.png)
![Form_error](https://user-images.githubusercontent.com/23316275/66488046-b6ccc800-ea83-11e9-9276-3aec56083096.png)

**Comment by goggo24** [comment]
We implemented a setting for changing the treshold for balck and white conversion (v.3.8.0+) - this should help.
