### ISSUE TITLE
styles.css breaks the question bank dropdown menus in moodle 3.8

### ISSUE THREAD

**Issue by webers-technikum-wien** [academic-moodle-cooperation/moodle-mod_offlinequiz#118]
as described here: https://tracker.moodle.org/browse/MDL-67305

offlinequiz styles.css changes the css for the question bank in line 856:

table#categoryquestions {
    width: 100%;
    overflow: hidden;
    table-layout: fixed;
}

the overflow:hidden breaks the new dropdown menus that were introduced in moodle 3.8

**Comment by univietw** [comment]
Thanks
We will have a look into that and fix it very soon.

**Comment by goggo24** [comment]
Looks fine now - v.3.8.0.
