### ISSUE TITLE
Images quality from the plugin is deteriorated and quizzes are mostly not recognised.

### ISSUE THREAD

**Issue by JadeTavernier** [academic-moodle-cooperation/moodle-mod_offlinequiz#119]
——— English version below

Sur notre moodle (3.7) depuis 1 mois les résultats de Offlinequiz sont très mauvais et nous n’arrivons pas à comprendre pourquoi.

Avant nous avions de bon résultats de reconnaissance sur papier blanc comme sur papier de couleur. Pourtant nous n’avions pas les prérequis  d’offlinequiz, Imagemagick et phpimagick n’était pas installés sur notre serveur ( ..??!)

Maintenant, la qualité des images que nous avons depuis le plugin est très dégradé et la reconnaissance des QCM se fait très mal.

Les seules modifications sur notre serveur sont a apriori  l’installation du paquet Texliv, Imagemagick6.9.7 et phpimagick.  

Nous avons essayé de desinstaller imagemagick et phpimagick, nous retrouvons de belles images dans le plug in offline mais la reconnaissance sur les papier de couleur est encore très mauvais (même avec le paramètre  fond gris clair ou sombre).

Avez vous une idée de vers où chercher la cause de tout cela ?
Comment cela marchait sans imagemagick ? 
Pourquoi l’installation d’imagemagick a dégradé la qualité des Scans importés ?

Bonne journée à vous

——————————————

For one month we've had met problems on our moodle (3.7) : the results of Offlinequiz are very bad and we can't understand the reasons why.

Before that, recognition results were good on white paper as well as on coloured paper. However, the prerequisites for offlinequiz, Imagemagick and phpimagick were not installed on our server (...??!)

Images quality from the plugin is deteriorated and quizzes are mostly not recognised.

The only modifications on our server are a priori the installation of the Texliv, Imagemagick6.9.7 and phpimagick package.  

We tried to uninstall imagemagick and phpimagick : images are ok in the offline plug but the recognition on colored paper remains very bad (even with the light grey or dark background setting).

Do you have any idea where to look for the origins of these problems?
How did it work without imagemagick? 
Why the installation of imagemagick has degraded the quality of imported scans ?

Best regards

**Comment by univietw** [comment]
Hi,
I can't understand why either. Did you maybe turn on the experimental evaluation? It is very new and not for production purposes at the moment.
We added a feature to convert the files to black/white a couple of releases ago. You can try disabling it by deleting/commenting the line 289
`                $this->convert_black_white($dirname . '/' . $file);`
or changing the threshhold in line 375
`$command = "convert " . realpath($file) . " -threshold 50% " . realpath($file);`
both in file offlinequiz/report/rimport/report.php

In general we recommend not to use coloured paper and scans should be in 200-300 dpi

**Comment by JadeTavernier** [comment]
——— English version below
Bonjour,

Merci pour votre retour, nous avons donc modifié la valeur du treshold à 75%.

Pour information, nous scannons les copies en niveau de gris, JPEG et 200 dpi.
Nous utilisons du papier blanc, vert, jaune, rose et bleu.

Avec la valeur du treshold à 75%, nous avons d'après nos premiers tests avec les différents papiers et avec des stylos bleu et noir, une bonne reconnaissance.

Nous passons donc en production avec cette valeur du treshold pour voir le résultat à plus grande échelle.

Bonne journée.

——————————————

Hello,

Thank you for your feedback, so we have changed the value of the treshold to 75%.

For information, we scan the copies in grayscale, JPEG and 200 dpi.
We use white, green, yellow, pink and blue paper.

With the value of the treshold at 75%, we have a good recognition according to our first tests with the different papers and with blue and black pens.

So we go into production with this treshold value to see the result on a larger scale.

Have a good day.

**Comment by univietw** [comment]
I'm happy this helped you to improve your recognition. I will put your feature in our backlog.

**Comment by goggo24** [comment]
We will make an admin setting for the treshold value - so that admins can set the value via browser.

**Comment by caiadogithub** [comment]
Hi,

I am experiencing the same problem ("Images quality from the plugin is deteriorated and quizzes are mostly not recognised.")

How do I set the 75% treshold. Need step by step instructions.

Thanks,

Ricardo

**Comment by univietw** [comment]
in file offlinequiz/report/rimport/report.php
change the line 375:
$command = "convert " . realpath($file) . " -threshold 50% " . realpath($file);
to the threshold of your choice.
The threshold feature will come with 3.8 in some weeks.

**Comment by caiadogithub** [comment]
It works at 75% threshold.

**Comment by goggo24** [comment]
We implemented a setting for changing the treshold for balck and white conversion (v.3.8.0+). Have fun!
