### ISSUE TITLE
About group

### ISSUE THREAD

**Issue by aurelienb1** [academic-moodle-cooperation/moodle-mod_offlinequiz#124]
Hi,

I'am not able to manage groups. Group A is always selected and i have no other options.

![BugGroup](https://user-images.githubusercontent.com/51001741/71838255-6535d880-3086-11ea-9558-ec190538c065.jpg)

Regards

**Comment by univietw** [comment]
you can change the amount of groups in the settings of your offlinequiz activity:

![Screenshot_2020-01-07 Editing Offline Quiz(1)](https://user-images.githubusercontent.com/17589223/71880300-48ee7600-3130-11ea-8a97-1561579af6b2.png)

**Comment by aurelienb1** [comment]
Oups, my bad.

Thank you
