### ISSUE TITLE
Where's the code logic of freezing randomly-added questions after creating forms?

### ISSUE THREAD

**Issue by fishfree** [academic-moodle-cooperation/moodle-mod_offlinequiz#125]
In Moodle built-in quiz, randomly-added questions cannot be frozen after saving the quiz. But I need this feature, so I need to learn this feature in this great offlinequiz. So could you please give me some tips?

**Comment by univietw** [comment]
I don't think this is possible without creating a core patch. The online quiz does basically the same. It would need a lock-feature in the question API to solve this issue.
