### ISSUE TITLE
user mapping errors

### ISSUE THREAD

**Issue by ndunand** [academic-moodle-cooperation/moodle-mod_offlinequiz#126]
The way `mod_offlinequiz` searches for a student starting from the `useridentification` setting is somewhat cumbersome and can lead to errors.

For us the error is that the wrong user DB record is being returned. The problem arises from the fact that we have in our DB several records returned by that `get_record` query, so only the first one is returned. This is the case because of old deleted or suspended users, which should not be taken into account here.

Seeing for instance the code in https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/blob/master/correct.php#L640 and in https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/blob/master/evallib.php#L131 and in some other places.

1. This should be factored, i.e. there should be a method or function addressing this (finding a course student given some `userkey`) consistently throughout the code. In particular, here `get_record('user', ...` should at least return only non-suspended, non-deleted users.

2. The subsequent query in https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/blob/master/correct.php#L649 should focus on capabilities rather than role archetypes to check whether a student is enrolled.

(this is somewhat related to #60)

**Comment by goggo24** [comment]
Bug fixed with v.3.9.0. - already published. Offlinequiz now recognizes, if there are multiple users with a given idnumber. It will choose the one in the course. Otherwise it will throw an error. Have fun!
