### ISSUE TITLE
Problem with embedding pictures

### ISSUE THREAD

**Issue by ralfoswaldkempfeld** [academic-moodle-cooperation/moodle-mod_offlinequiz#135]
Hello everyone,
in the settings/form settings you can edit the displayed info text of the question page.
But unlike the default, you can't insert images with the "Insert or edit images" button. What is wrong?
 
Best Regards
Ralf Oswald

**Comment by univietw** [comment]
This seems to be a bug. Which question page format do you use? Latex, DocX or PDF?

**Comment by univietw** [comment]
@bobopinna this definitely isn't the same issue as described. Could you open another issue for that?
