### ISSUE TITLE
How can I force image recognition to be started immediately?

### ISSUE THREAD

**Issue by tobias75germany** [academic-moodle-cooperation/moodle-mod_offlinequiz#136]
After importing a pdf with 2 or 3 pages, it takes around 5 min. until page recognition is complete and quiz results are shown. The moodle crontab is executed every minute, and even invoking the cronjob manually doesn't help. Is there any way to see what the offlinequiz module is actually doing and why it takes so long?
Moodle Version is: 3.8.2+
Offlinequiz module version is: v3.8.0

Any hints appreciated.

**Comment by univietw** [comment]
the offlinequiz cronjob only runs every 10 minutes. you can change this in admin-config->server->scheduled tasks.
The tasks name is \mod_offlinequiz\task\page_evaluation_task and you can change it to every minute if you want. Every page takes about 10-20 seconds (depending on your CPU)

**Comment by ndunand** [comment]
If you want to see how the scheduled task behaves in real-time, you can see [this section of the documentation](https://docs.moodle.org/39/en/Offline_quiz_activity#Cronjob). I actually use this setup on our production systems: disable the scheduled task in Moodle completely and have this separate cron task run the image recognition. If you launch it manually in the command-line you can check exactly what happens and when.

**Comment by goggo24** [comment]
We just published an admin report for offlinequiz.  The Offlinequiz-Cron Module adds an interface to the offlinequiz-module to see and change pending cronjobs in the offlinequiz => https://github.com/academic-moodle-cooperation/moodle-report_offlinequizcron. Have fun!
