### ISSUE TITLE
Guidance with "Not Adjusted" Error

### ISSUE THREAD

**Issue by Andrewolico** [academic-moodle-cooperation/moodle-mod_offlinequiz#137]
Hi there,

Could you please point me to a solution for "not adjusted" error. I'm using moodle 3.5 and uploading jpeg images. Some of the images are working as expected but others aren't. I have tried to readjust the crosses on the uploads that are "Not adjusted".

![image](https://user-images.githubusercontent.com/20690233/100190568-34a59a00-2ef7-11eb-906b-e71adcd2fc33.png)

It also does not recognise the page number and returns a "?"

![image](https://user-images.githubusercontent.com/20690233/100190410-dc6e9800-2ef6-11eb-88f2-6aaf7864eb9c.png)

Appreciate your assistance and thanks for a great plugin.

Andrew

**Comment by goggo24** [comment]
Sorry for coming back so late - does the error still occurs? Normally you have to readjust the blue page crosses. It looks like the screenshot is cut off, so its hard to say what's the problem, but maybe the the 2 crosses on the bottom are not placed correctly.

**Comment by oliviervalentin** [comment]
Hi,
I discover this thread very lately, but for the first time, I got the same problem. 

I'm running with Moodle 3.11.8+ and the latest version of Offline Quiz. I encounter the same problem with a perfectly clean sheet : student crosses are clean, no unwished lines, all blue crosses are well located, and ID number and group are well recognized. 
But strangely, copy shows are error message "Not adjusted".

- If I try to move crosses, grid moves and ID number is not recognized.
- If I try to change something (group, ID number), Offline Quiz doesn't recognize them (logical !).

I event tried with Photoshop to assembly ID number and answers on a copy which was successfully corrected, no result.

Is there anything to try to solve this problem ?

Olivier

**Comment by mediaenlab** [comment]
Hi, 
I'm having the same problem on my side, at random. One hypothesis: the scanner configuration (resolution or TIFF options in my case) results in a file that is sometimes difficult to interpret for optical recognition. 
Jean
