### ISSUE TITLE
PNG images not supported

### ISSUE THREAD

**Issue by gjalam** [academic-moodle-cooperation/moodle-mod_offlinequiz#138]
Hello,
I have been using the "Offline Quiz" plugin for several years.
Recently we upgraded to Moodle version 3.93+ and today I'm having a problem using this plugin. I uploaded the exam sheets (there are 60) as a single PDF file but I get the following error:

```
"PNG images not supported"

error/Could not load file

More information about this error

×Debug info:
Error code: Could not load file
$a contents:
×Stack trace:
line 498 of /lib/setuplib.php: moodle_exception thrown
line 513 of /mod/offlinequiz/report/rimport/scanner.php: call to print_error()
line 125 of /mod/offlinequiz/correct.php: call to offlinequiz_page_scanner->load_stored_image()
```

Do you have a solution for me to solve this problem? No sheet is read by the plugin.
Sincerely, I wish you a happy New Year's Eve.

**Comment by univietw** [comment]
hello,
the feature with pdf is relatively new-ish (i think 3-4 versions old)
What it basically does after uploading is taking pages of the pdf and converting each of them to a seperate picture file imagemagick.
My best guess is that your moodle server has no imagemagick installed. Can you make sure both imagemagick and the php module for it are running?

If you have problems deleting the job you can install https://github.com/academic-moodle-cooperation/moodle-report_offlinequizcron which is also from us and helps with managing the correction tasks.

**Comment by gjalam** [comment]
Thank you for your reply.
I created a php file (see below) to test if ImageMagick is well installed as well as if the php extension Imagick is well loaded. Both are there! Do you have other alternative to explore?
Best regards,
Gabriel

<?php
//This function prints a text array as an html list.
function alist ($array) {
  $alist = "<ul>";
  for ($i = 0; $i < sizeof($array); $i++) {
    $alist .= "<li>$array[$i]";
  }
  $alist .= "</ul>";
  return $alist;
}
//Try to get ImageMagick "convert" program version number.
exec("convert -version", $out, $rcode);
//Print the return code: 0 if OK, nonzero if error.
echo "Version return code is $rcode <br>";
//Print the output of "convert -version"
echo alist($out);
if (extension_loaded('imagick'))
    echo 'Imagick is loaded';
?>

'''''''''''''''''''''''''''''''''''''''''''''''''''
Version return code is 0
Version: ImageMagick 6.9.10-68 Q16 x86_64 2020-12-15 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(3.1)
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff wmf x xml zlib
Imagick is loaded
'''''''''''''''''''''''''''''''''''''''''''''''''

**Comment by gjalam** [comment]
Hello All,
The php GD extension was missing. Now the problem is solved.
Best regards,
