### ISSUE TITLE
Falsche User in der "Potential Members"-Liste

### ISSUE THREAD

**Issue by frankkoch** [academic-moodle-cooperation/moodle-mod_offlinequiz#14]
Guten Tag Frau Karall
 
Ich bin ein Fan von Ihrem Moodle Offline Quiz und wir haben das Modul an unserer Hochschule installiert.  Nun werden aber leider in der «Potential Members» Liste neben den in dem betreffenden Kurs eingeschriebenen Teilnehmenden auch User mit einer System-Rolle angezeigt:
![participants list](https://cloud.githubusercontent.com/assets/12372991/12947101/727761f4-cff9-11e5-8915-51eccd042cd4.JPG)

Die im Attachment markierten User sind nicht in dem betreffenden Kurs eingeschrieben, haben bei uns aber eine System-Rolle (https://docs.moodle.org/30/en/Assign_roles#System_context). Aus meiner Sicht sollten diese User nicht in der «Potential Members» Liste gelistet werden. Lässt sich das allenfalls ändern? Vielen Dank für Ihre Hilfe und ein Feedback, falls dann eine geänderte Version zur Verfügung steht.
 
Mit Gruss, Frank Koch
~~
Prof. Frank Koch, Dozent für Wirtschaftsinformatik
HSR Hochschule für Technik Rapperswil (FHO)
Fon: +41 79 342 89 91, Web: http://www.hsr.ch

**Comment by kaspot** [comment]
Lieber Herr Koch, 
dürfte ich Sie noch um die Moodle Version bitten, die Sie bei sich installiert haben. Wir werden es auf jeden Fall an unseren Entwickler weiterleiten.

**Comment by frankkoch** [comment]
Vielen Dank für die Weiterleitung. Wir arbeiten mit Moodle 3.0.2.

**Comment by kaspot** [comment]
Können wir hier vielleicht noch genauere Informationen zu den "System-Rollen" bekommen. Welche Rolle / Archetyp,....

**Comment by frankkoch** [comment]
Auf unserem Moodle-Server verwalten wir (Dashboard ► Site administration ► Users ► Permissions ► Define roles) eine Rolle, die bei uns auch eine System-Rolle ist (Dashboard ► Site administration ► Users ► Permissions ► Assign system roles).

Die dort eingetragenen User erscheinen zu unserer Verwunderung im Offline Quiz in der Liste der "Potential members". Ich sende euch gerne unsere Einstellungen zu dieser Gruppe, möchte das aber nicht auf dem Forum tun. Wohin könnte ich diese Daten senden?

**Comment by kaspot** [comment]
Ich habe gesehen, dass Sie mittlerweile auch mit Frau Eva Karall in Kontakt sind und uns auch die Liste bereits zukommen haben lassen. Aus diesem Grund schließe ich das Ticket hier.
