### ISSUE TITLE
Design adaptations

### ISSUE THREAD

**Issue by LisaE14** [academic-moodle-cooperation/moodle-mod_offlinequiz#145]
In Classic Theme under "Edit group questions" and "Grades" some CSS adaptations would be great :)
![Fragenliste bearbeiten](https://user-images.githubusercontent.com/68582211/117131594-ea77ed00-ada1-11eb-8349-6b508bc1c26d.png)
![Bewertungen](https://user-images.githubusercontent.com/68582211/117131598-eb108380-ada1-11eb-846e-74794adc076e.png)

**Comment by univietw** [comment]
Which version of offlinequiz and moodle do you use?

**Comment by LisaE14** [comment]
We use Moodle 3.9.6+ (Build: 20210423) and Offline Quiz 2020060800.

**Comment by LisaE14** [comment]
In Moodle 3.10.6 with Offline Quiz 2020110501 it becomes a little bit better:

![Bewertungen](https://user-images.githubusercontent.com/68582211/128679833-cda2101b-dae0-49eb-858e-562731e60b19.png)
![Fragenliste](https://user-images.githubusercontent.com/68582211/128679837-0e53f97a-a3d7-4016-8ffa-9d452928b306.png)

Except for the missing lower margin/padding at 1.00 in the grades, I was able to correct that with this CSS:
```
/* Grades */
#page-mod-offlinequiz-edit ul.slots li.section li.activity.forgrading .activityinstance {
  left: 3.7em;
}

/* Edit group questions */
#page-mod-offlinequiz-edit ul.slots .activityinstance img.activityicon {
  padding:0;
}

#page-mod-offlinequiz-edit .section .activity .actions {
  display: block;
}
```
It would be great if you could take over it.

**Comment by LisaE14** [comment]
In Moodle 3.11.5+ and Offline Quiz 2021070801 we still need my CSS adaptions above. Is it possible that you check it with Classic Theme?
