### ISSUE TITLE
Statistics problem in environment with Oracle DB

### ISSUE THREAD

**Issue by jaume77** [academic-moodle-cooperation/moodle-mod_offlinequiz#146]
Hi,
At the Autonomous University of Barcelona (UAB), we use the Moodle environment on an Oracle database. Some time ago we opened an issue that was finally solved and we have been able to offer the Offlinequiz module in our Virtual Campus.

Moodle 3.8.1
Offlinequiz 2020020100 (From what I have checked in you repository, the latest version of the module has the same query)

Currently we have another problem, in this case, when accessing the statistics of an Offlinequiz activity.
For example, when clicking on the "Statistics" tab of an activity with 3 groups, the exams of the 3 groups with 20 questions, and a total of 69 students who have answered, the screen keeps loading, until it returns an error. (attached image, sorry it's so long ).

> Debug info: ORA-01652: no se ha podido ampliar el segmento temporal con 128 en el tablespace TEMP
> 
> Stack trace:
> 
>     line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
>     line 277 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->query_end()
>     line 1180 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->query_end()
>     line 131 of /mod/offlinequiz/report/statistics/qstats.php: call to oci_native_moodle_database->get_records_sql()
>     line 1111 of /mod/offlinequiz/report/statistics/report.php: call to offlinequiz_statistics_question_stats->load_step_data()
>     line 1264 of /mod/offlinequiz/report/statistics/report.php: call to offlinequiz_statistics_report->compute_stats()
>     line 217 of /mod/offlinequiz/report/statistics/report.php: call to offlinequiz_statistics_report->get_offlinequiz_and_questions_stats()
>     line 115 of /mod/offlinequiz/report.php: call to offlinequiz_statistics_report->display()

Indicate that the Oracle temp memory has been expanded to 57Gb, but it continues to fill it.

Would it be possible to "optimize" the query it generates?

Thank you!
Jaume R. 

![Screenshot_2021-05-06 Error](https://user-images.githubusercontent.com/2485232/117308181-917f8600-ae81-11eb-8fdb-c734fdef17e4.png)

**Comment by goggo24** [comment]
@jaume77 does the error still occurs with a higher version of offlinequiz?

**Comment by mwreichel** [comment]
Hi @jaume77,
we plan to fix this bug in the next version of the plugin too.
It would be great if you could test it after that with oracle DB and give us feedback. We will contact you directly for this.

All the best,
Martin

**Comment by jaume77** [comment]
Hi!

At our university, we start the course with a clean Moodle instance, installing from 0

In the Moodle environment of course 22-23 (Moodle 3.11), there are 91.591 records in the m_user table and 434.681 records in the m_question table.

In the Moodle environment of course 23-24 (Moodle 4.1) there are 88.998 records in the m_user table and 276.435 records in the m_question table.

We usually export from a production environment to a test environment to perform tests.

Thanks
Jaume R.


________________________________
De: univietw ***@***.***>
Enviat el: dijous, 11 de gener de 2024 15:25
Per a: academic-moodle-cooperation/moodle-mod_offlinequiz ***@***.***>
A/c: Jaume Rocarias Oraa ***@***.***>; Mention ***@***.***>
Tema: Re: [academic-moodle-cooperation/moodle-mod_offlinequiz] Statistics problem in environment with Oracle DB (#146)

No soleu rebre correu de ***@***.*** Descobriu per què aquest fet pot ser un problema<https://aka.ms/LearnAboutSenderIdentification>

@jaume77<https://github.com/jaume77> can you tell me how many users and questions you have in your test?

**Comment by cmichale** [comment]
To Whom It May Concern,
 
 I am out of office until 05 Feb 2024.

In the meantime please contact
- for questions concerning e-learning including BOKUlearn: ***@***.***
- for questions concerning didactics in higher education: ***@***.***

Best regards,
Claus Rainer Michalek

>>> univietw ***@***.***> 29.1.24 17:55 >>>

Hey @jaume77, I completely rewrote this query and it would be nice to know if it fixes your bug. I pushed a 4.1-Branch with the updated query to the branch: 146_stats_error

**Comment by jaume77** [comment]
Sorry for the delay

I have tried modifying the `report/statistics/qstats.php` file, and indeed, where the error was previously displayed, it now loads the statistics.

The complete test consisted of:

Moodle 4.1 environment
Offlinequiz version 2023070701
Table m_user: 90.015 records
Table m_question: 395.322 records

In an activity like the one shown in the image:

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/1ffcd140-8fc7-47eb-8cb0-d60c66960266)

When accessing **"Statistics" -> "Resum"** after several time of loading the image error is shown (wach  the scroll):

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/d4577e7f-c1af-4a33-93e5-1d2131838ae8)

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/64122b5a-441f-4115-8502-0cbac0aa463a)

After replacing the indicated file, accessing **"Statistics" -> "Resum"**, after a few seconds, the image statistics are displayed, as well as the different statistics screens..

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/5a97c681-1e6b-47f0-87c9-7115c3118301)

When you press **"Recalculate now"**, they are recalculated in a few seconds.

So it seems that the problem has been solved!

Thank you so much!!

Already waiting for the version for Moodle 4.3 for the 24-25 course :-)

**Comment by jaume77** [comment]
a problem :

Applying the indicated change, the "**Facility Index**" calculation **is always shown at 100%**:

In this activity, which due to its configuration previously loaded the statistics

**Without the change:**

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/d670e8b5-27f6-4338-ad8b-7ac71196094f)

**With the change :**

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/15484241-5cd3-439b-af82-5a7a0250f3f1)

However, the "**Question and answer analysis**" section, "**Partial credit**", "**Count**" and "**Frequency**" they seem correct :

**Without the change:**

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/5792b0d3-184d-45ed-9eb0-7ff1a3812b3d)

**With the change :**

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/b3eb01b0-6ec3-4733-af1d-1357b51d59ff)

Thanks!

**Comment by mwreichel** [comment]
Hi @jaume77,

thanks for your further comment on that.
This was related to another bug which is fixed with the coming up minor version of 4.3
