### ISSUE TITLE
Error installing 3.11.0 on Moodle 3.11 with MariaDB

### ISSUE THREAD

**Issue by foxlapinou** [academic-moodle-cooperation/moodle-mod_offlinequiz#149]
Hi,
I'm installing a new Moodle 3.11 platform, starting from scratch.
When installing mod_offlinequiz 3.11.0 on Moodle 3.11 with MariaDB, i had (at least with debug mod on developper level) this error :
Warning: A non-numeric value encountered in /var/www/html/moodle/lib/ddl/mysql_sql_generator.php on line 160

And when i launch the command "php admin/cli/check_database_schema.php", i get :
offlinequiz_scanned_pages
 * column 'info' length is 255, expected  (C)

I think a column is not well defined.

**Comment by goggo24** [comment]
included in v.3.11.2
