### ISSUE TITLE
Missing display of points for each question item 

### ISSUE THREAD

**Issue by frankkoch** [academic-moodle-cooperation/moodle-mod_offlinequiz#15]
Each questions within a quiz has assigned points. This is important information for students while taking the exam. However, Offline Quiz does not display the points for a question neither on the question nor on the answering sheet.

**Comment by goggo24** [comment]
Per default the points of a question are not printed, but you can acitvate it in the administration settings of each offline test: **Form settings => Print question grades**. Then the points are printed on the question forms. Did it work?

![question_grades](https://cloud.githubusercontent.com/assets/16721900/13872388/aefeda90-ecea-11e5-9ce8-7c809369cca9.png)

**Comment by frankkoch** [comment]
You're right. Yes, this does the job. Thak you Eva.
