### ISSUE TITLE
CLI cron run not possible anymore

### ISSUE THREAD

**Issue by ndunand** [academic-moodle-cooperation/moodle-mod_offlinequiz#150]
This modification 

https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/commit/8004a8adc2a9aacc89ebf679025f891eb9105f2f#diff-235879a97076d4b9559b67a633b094fbe18cdbbe115b5293547758c8cf10b351R33

breaks the possibility to run the cron job separately as detailed in https://moodle.org/plugins/mod_offlinequiz/v3.11.0/24338

> If you want to run the cron job on a dedicated server you have to disable it in the moodle settings and create an additional job on the dedicated server looking like this:
> 
> */10 * * * * DATE=`date +\%Y\%m\%d`; php <your moodle root dir>/mod/offlinequiz/cron.php --cli=1 >> /var/log/moodle/cron-olq.log.$DATE 2>&1

**Comment by goggo24** [comment]
Thanks for reporting - we will have a look.

**Comment by goggo24** [comment]
info updated v.3.11.2
