### ISSUE TITLE
Do not generate math equation (MathType by WIRIS plugin) into pdf

### ISSUE THREAD

**Issue by thaygiaoth** [academic-moodle-cooperation/moodle-mod_offlinequiz#153]
I'm insert math equations using MathType by WIRIS plugin

It's display on web

![image](https://user-images.githubusercontent.com/10233106/131139013-0d7bdf93-de67-43c4-91c1-2e3c736c7af2.png)

but it's not display on pdf

![image](https://user-images.githubusercontent.com/10233106/131138965-e652c687-9ab5-4b71-8f42-5e1423519a0f.png)

Please fix it, thank you very much!

**Comment by univietw** [comment]
It seems you haven't installed the latex libraries. Can you try installing them and see if this helps?

**Comment by thaygiaoth** [comment]
@univietw could you please give me more details guide
