### ISSUE TITLE
Multiple lists not working in participant_correct.php

### ISSUE THREAD

**Issue by emilioah** [academic-moodle-cooperation/moodle-mod_offlinequiz#155]
Automatic attendance (uploading files) doesn't work when you use two lists or more.

When you have more than one list (at least two lists) if you are going to import lists of the participants in upload/correct tabs (two or three files) , only the first list works, the system checks the participants included in the first list but not the participants in the other lists.

**Comment by LisaE14** [comment]
We have the same problem. Moodle 3.10.7 and offlinequiz v3.10.1 (2020110501)

**Comment by MWRAMC** [comment]
Hi,
sorry for our late answer. Now we had time to have a look on this, but weren't able to reproduce it with Moodle 3.11 or 4.0.
Therefore I already added this case to our general tests and watch for possible recurrence.
We will close this issue, but we would be glad if you let us know if it happens again, to find out more about this behaviour to be able to solve it.
