### ISSUE TITLE
No indication of difference between MC questions with one respectively multiple right answers.

### ISSUE THREAD

**Issue by frankkoch** [academic-moodle-cooperation/moodle-mod_offlinequiz#16]
Students need to know whether they can mark one answer only or several. In case of a MC question with one right answer only, the student answer become invalid if she/he marks an additional answer. This is not OK.

Moodle also distinguishes MC questions with one right answer from questions with multiple right answers. While MC with one right answer may result in negative points, MC with multiple answers cannot result in less than 0 points. Thus, students need to know whether they can mark just one or multiple answers. 

In CBA this is usually indicated by using circles for one right answer and squares for multiple right answers. Maybe the same convention could be used on the question and answer sheets.

**Comment by kaspot** [comment]
Hi, 
thanks for your feedback. May I ask you what exactly CBA is? And the second question would be: How does Moodle standard Quiz deal with this? We are trying to be as close to Moodle Core as possible, so it would be really useful to know how Moodle Core behaves. 
Thanks.

**Comment by frankkoch** [comment]
Sorry for the confusion.
CBA = computer based assessment

The grading algorith used by Offline Quiz is just fine and identical to the Core Online Quiz. The difference is, that in an Online Quiz the user interface prevents students to cross more than one answering option in case of a MC quest with one right answer. They simply cannot. Also, MC questions with one answering option are indicated by a circle, while MC questions with multiple right answers are indicated by squares.
![capture1](https://cloud.githubusercontent.com/assets/12372991/13979948/ff98ef96-f0db-11e5-9275-7233f226faf6.JPG)
versus
![capture2](https://cloud.githubusercontent.com/assets/12372991/13979975/2464f842-f0dc-11e5-938a-fed95a00d2e4.JPG)


In the Offline quiz nothing stops a student on paper to cross more than one option in case of a MC quest with one right answer only, and there is no indication (circle, square) whether one or multiple answers might be right.

In my opinion there should be a printed information with each question whether one or multiple answers might be right. Currently, our soluton is to provide this information within each question text, but this is error-prone when quieston types are changed. It would be better if Offline Quiz would clearly identicate the type of MC question (one versus multiple right answers).

Please let me know if there still is confusion.

**Comment by kaspot** [comment]
Hi, 
thank you for the very detailed information. I will forward this issue to our team and we will discuss it.

**Comment by kaspot** [comment]
We fixed the problem and it will be available with the new Moodle 3.1.x version. This Offline Quiz version will be available in September. Closing it for now — hope it will solve your issue :-)
