### ISSUE TITLE
Image type not supported when uploaded as PDF

### ISSUE THREAD

**Issue by greshtl22** [academic-moodle-cooperation/moodle-mod_offlinequiz#162]
We have the problem that results uploaded as pdf, either single or multiple ones in one file, result in the error “Image type not supported”. Uploading them either as single images or as zip containing multiple ones works fine. Is there anything special to be configured for pdf uploads to work?

**Comment by goggo24** [comment]
Have you installed imagemagick? You need to have imagemagick and the relating php module (http://pecl.php.net/package/imagick) installed. If yes, which version of our plugin do you use?

**Comment by greshtl22** [comment]
Yes, we have ImageMagick and the imagick php plugin installed. We just installed your plugin and imagemagick and thus should have the most recent versions of everything. We have Version v3.11.1 (2021070801) of your plugin.

**Comment by goggo24** [comment]
Unfortunately I have no further idea, what else you could do. Which version of imagemagick do you use? Can you maybe send me an example of your pdf-file (to eva.karall@univie.ac.at), than i can try it on our instance.

**Comment by greshtl22** [comment]
We tried various things, but we were not able to fix the problem. Thus, we have now decided to use a different solution. Thank you anyway for you support and good work!
