### ISSUE TITLE
System says "Pages incomplete"

### ISSUE THREAD

**Issue by a-camacho** [academic-moodle-cooperation/moodle-mod_offlinequiz#163]
Hi,

We have been using Offline Quizz without almost any problem.
Yesterday 300 copies have been scanned and uploaded to Moodle.

On those 300 copies, 4 students had an error we never saw before : "Pages incomplete".

![Capture d’écran 2022-01-19 à 12 14 29](https://user-images.githubusercontent.com/29976133/150119634-5acbf8ea-23a6-497e-9ebc-09e70b8aa693.png)

System seems to work as : 
- Student id_number is correctly OCR'ed and detected
- Student answers are also detected and calculated

![Capture d’écran 2022-01-19 à 12 17 43](https://user-images.githubusercontent.com/29976133/150119806-5429bad5-a247-4fb6-8379-193404a89df1.png)

Do you have any informations about this error ? What could it mean ?
How can we correct ? You can see that when user is missing we can "correct" but for those students button shows "Show".

Thanks a lot !

**Comment by blanderson22** [comment]
This may help ... we have a 2-page answer sheet and we receive the "Pages incomplete" error when only 1 of the 2 pages for a student is uploaded. Or, both pages are uploaded but only 1 page has the id number identified at that point. 

The error corrects itself when the second page is uploaded, or if already uploaded, the second page is corrected so the ID number is properly attributed to the student.

**Comment by goggo24** [comment]
Sorry for coming back so late. Thanks @blanderson22 for answering - the answer describes exactly how the test should behave, when there is more than one page. But if I interpret the screenshot correctly, this is a one page test - so it looks like as if the pagenumber couldn't be interpretated correctly. 

@a-camacho have you found a solution? Has the error (with a higher offlinequiz version) occured again?

**Comment by acamacho-unige** [comment]
> @a-camacho have you found a solution? Has the error (with a higher offlinequiz version) occured again?

It seems that the problem indeed appeared when only some pages were recognized.
With higher versions (and actual version of Moodle) we do not have this problem anymore.

This issue can be closed for us, for now.

Thanks a lot, and sorry for the delayed reply.

**Comment by LisaE14** [comment]
Guten Tag,

ich bin bis einschließlich 9. Jänner 2024 nicht im Büro.
In dringenden Fällen wenden Sie sich bitte an meine Kolleg*innen unter der DW 1111 oder per E-Mail an ***@***.***

Mit freundlichen Grüßen
Lisa Eckerstorfer

>>> acamacho-unige ***@***.***> 01/04/24 09:42 >>>

> @a-camacho have you found a solution? Has the error (with a higher offlinequiz version) occured again?

It seems that the problem indeed appeared when only some pages were recognized.
With higher versions (and actual version of Moodle) we do not have this problem anymore.

This issue can be closed for us, for now.

Thanks a lot, and sorry for the delayed reply.

**Comment by mwreichel** [comment]
Hi @a-camacho ,
thank you for your feedback.

All the best,
Martin
