### ISSUE TITLE
Need help marking answer pages: answers are not being read

### ISSUE THREAD

**Issue by ncal-4on** [academic-moodle-cooperation/moodle-mod_offlinequiz#164]
Hi there,
Looking for some help on this. I'm new to offlinequiz plugin and I'm testing it for my team's use. 
Moodle 3.11.6+
Offline Quiz 3.11.2

I am having challenges getting this to work and I'm stuck.  
-	I have finally been successful in getting this to read the image, but it only reads the id number and does not detect any of the answers (no green squares in the answer area, see image below)
-	It also says that the user does not exist in the system, but I created this user in Moodle and enrolled in the course
o	Note: I did use this same user ID to test initially, when the user was NOT enrolled into Moodle or the course.  I kept the scan in the results for my reference, and similar to below, it read the user ID, but none of the answers
-	Not sure if this makes a difference but the printed page is a letter size, and when I scan in the answer form, I select an A4 size to make it work
![image](https://user-images.githubusercontent.com/97301038/164460640-146c5111-3675-4bcb-805a-27d4dd406ed0.png)

A few of questions:
•	Any suggestions how I can fix the above of not being able to read the answers?
•	Each scan is currently taking at least 5 mins to load, any suggestions on this?
•	Is there a better way to use the US letter size paper work with the A4 size setting of the plugin?
•	Can the send notification by email message be disabled?
•	Can marks be calculated by section?

Any help or suggestions are appreciated.  I have looked through several videos and documentation, I don't know if I'm just missing it.  I should note that I can generally understand, but I am not highly technical.
Thanks

**Comment by goggo24** [comment]
As long as the user is not found from offline test routine, the sheet will not be evaluated. Which field have you used for user identification? In this profile field "9008128" must be entered there.
![grafik](https://user-images.githubusercontent.com/16721900/164779409-12aacdd3-b89d-406e-a2d9-c3121d59ee45.png)

**Comment by ncal-4on** [comment]
Ahhhh right!  This may be it!  I will try.  

Thanks very much.
