### ISSUE TITLE
Non-removable questions after deleting offlinequiz that uses them

### ISSUE THREAD

**Issue by jaume77** [academic-moodle-cooperation/moodle-mod_offlinequiz#165]
Hello!,

It seems that it is a bug.

When deleting an activity "Offlinequiz", the questions that were assigned to it continue to appear in use, even if they are not used in any other activity in the classroom.

Steps to follow :

1) In an empty course, create 1 "multiple choice" type question
2) Create an "Offlinequiz" activity
3) Assign to this activity, the question created
4) Generate the forms
5) Delete the activity (also delete it from the recycle bin, if it is activated)
6) Attempt to remove the question from the question bank

A message will appear indicating that the question is still being used.

![image](https://user-images.githubusercontent.com/2485232/151151858-436d7795-5c92-4a3b-9727-4bfe0db4f017.png)

This behavior has been verified in 2 different environments:

- Moodle 3.10.3 (Oracle DB) - Offlinequiz 2020110500
- Moodle 3.3.6 (Mysql) - Offlinequiz 2017081102

Thanks!

Jaume R.

**Comment by goggo24** [comment]
Thanks for reporting. I could reproduce the bug with our 3.11.x version too. We will add it to our board.

**Comment by mwreichel** [comment]
Hi @jaume77,
we plan to fix this bug in the next version of the plugin too.
It would be great if you could test it after that with oracle DB and give us feedback. We will contact you directly for this.

All the best,
Martin

**Comment by mwreichel** [comment]
Hi @jaume77,
we fixed this bug and it will be available in the coming up minor-versions of 4.3, 4.2 and 4.1 soon.

Thanks for reporting.
Martin
