### ISSUE TITLE
SVG not supported on PDF format

### ISSUE THREAD

**Issue by Syl20D20** [academic-moodle-cooperation/moodle-mod_offlinequiz#166]
Hello,

I recently noticed that the SVG format is not accepted when exporting the exam paper to PDF. The images do not appear while in JPG format it works. Is it a bug?

Thank you.

**Comment by goggo24** [comment]
Thanks for reporting. Do you get any error code in the pdf? Does it work with docx as a workaround?

**Comment by Syl20D20** [comment]
I tested again and it seems to work now. Maybe an update fixed the problem.
