### ISSUE TITLE
Wrong traslation string in pdflib.php

### ISSUE THREAD

**Issue by emilioah** [academic-moodle-cooperation/moodle-mod_offlinequiz#168]
Wrong translation string for "group" in the code of pdflib.php:

You are calling the core language string with "get_string('group')" instead of the plugin language string with "get_string('group','offlinequiz')".

**Comment by goggo24** [comment]
Thanks for reporting. We will have a look!

**Comment by goggo24** [comment]
Fixed in v.3.11.4.
