### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Jason505Cze** [academic-moodle-cooperation/moodle-mod_offlinequiz#170]
Hey there,
we have problem running this plugin on PHP8, or even 7.4, as e.g. using curly braces in array access ($usernumber{$i}) is deprecated. Have you considered any code updates?

Thanks.

**Comment by univietw** [comment]
This issue is going to be fixed with the upcoming version 3.11.4
Thanks again for the report.

**Comment by goggo24** [comment]
v.3.11.4 has been just published. Have fun!
