### ISSUE TITLE
Workshop Anfrage

### ISSUE THREAD

**Issue by julialeede** [academic-moodle-cooperation/moodle-mod_offlinequiz#171]
Wir würden gerne einen Workshop zur Einführung des Plugins anbieten. Gäbe es jemand im Team, der Interesse daran hätte?
Viele Grüße Julia

**Comment by goggo24** [comment]
Liebe Julia,

wir bieten als AMC einige Anleitungen an:
- Cheat Sheet: "Offline-Tests durchführen(http://www.academic-moodle-cooperation.org/fileadmin/user_upload/p_aec/Cheat_Sheets/Offline-Tests_durchfuehren-DE.pdf)
- Offline-Test - Ergebnisse herunterladen und auswerten"(http://www.academic-moodle-cooperation.org/fileadmin/user_upload/p_aec/Cheat_Sheets/Offline_Test_-_Ergebnisse_herunterladen_und_auswerten-DE.pdf)
- Video-Tutorial: "Offline-Tests durchführen" (http://www.academic-moodle-cooperation.org/dokumentation/multimedia-tutorials-auf-youtube/offline-tests-durchfuehren/)

Weiters könnt ihr auch gerne die Anleitungen der Uni Wien verwenden:
- Technische Umsetzung mit Offline-Tests in Moodle (https://zid.univie.ac.at/fileadmin/user_upload/d_zid/open/studium-lehre-forschung-it-kurse/e-learning/technische_umsetzung_offline_tests.pdf)
- Erstmalige Durchführung von Multiple-Choice-Prüfungen – Tipps und Empfehlungen (https://zid.univie.ac.at/fileadmin/user_upload/d_zid/open/studium-lehre-forschung-it-kurse/e-learning/erstmalige_durchfuehrung_mc_pruefungen.pdf)

Falls die Anleitungen nicht ausreichen, stelle bitte eine Anfrage unter https://www.academic-moodle-cooperation.org/kontakt/ an uns. Danke.

lg Eva

**Comment by julialeede** [comment]
Liebe Eva,


prima, danke dir! Wir kennen eure Anleitungen, hatten aber z.T. Probleme bei der konkreten Umsetzung. Ich schau mir das den Monat durch an und meld mich bei Problemen noch mal.


Herzliche Grüße
Julia


________________________________
Von: Eva Karall ***@***.***>
Gesendet: Donnerstag, 14. April 2022 16:57
An: academic-moodle-cooperation/moodle-mod_offlinequiz
Cc: Julia Lee; Author
Betreff: Re: [academic-moodle-cooperation/moodle-mod_offlinequiz] Workshop Anfrage (Issue #171)


Liebe Julia,

wir bieten als AMC einige Anleitungen an:

  *   Cheat Sheet: "Offline-Tests durchführen(http://www.academic-moodle-cooperation.org/fileadmin/user_upload/p_aec/Cheat_Sheets/Offline-Tests_durchfuehren-DE.pdf)
  *   Offline-Test - Ergebnisse herunterladen und auswerten"(http://www.academic-moodle-cooperation.org/fileadmin/user_upload/p_aec/Cheat_Sheets/Offline_Test_-_Ergebnisse_herunterladen_und_auswerten-DE.pdf)
  *   Video-Tutorial: "Offline-Tests durchführen" (http://www.academic-moodle-cooperation.org/dokumentation/multimedia-tutorials-auf-youtube/offline-tests-durchfuehren/)

Weiters könnt ihr auch gerne die Anleitungen der Uni Wien verwenden:

  *   Technische Umsetzung mit Offline-Tests in Moodle (https://zid.univie.ac.at/fileadmin/user_upload/d_zid/open/studium-lehre-forschung-it-kurse/e-learning/technische_umsetzung_offline_tests.pdf)
  *   Erstmalige Durchführung von Multiple-Choice-Prüfungen – Tipps und Empfehlungen (https://zid.univie.ac.at/fileadmin/user_upload/d_zid/open/studium-lehre-forschung-it-kurse/e-learning/erstmalige_durchfuehrung_mc_pruefungen.pdf)

Falls die Anleitungen nicht ausreichen, stelle bitte eine Anfrage unter https://www.academic-moodle-cooperation.org/kontakt/ an uns. Danke.

lg Eva
