### ISSUE TITLE
Incorrect formatted text in .Docx printout version

### ISSUE THREAD

**Issue by quochung2310** [academic-moodle-cooperation/moodle-mod_offlinequiz#172]
In the questions which have some ordinary format like italic, underline and bold, the export file in Word format has shown incorrect formatted text, and sometime jumped to the next line randomly. For example:

Question 1:
A. This is the ***orig***inal answer

The exported file in .docx format:

Question 1:
A. This is the _orig_
inal answer

To my surprise, it is normal in pdf format, but docx is the one I need to re-format page as needed.
Hope to solve this soon.

**Comment by AcademyPop** [comment]
Hi. You can always use a 'pdf to docx converter' if you want, by the way, i didn't know there was a docx option in the plugin, i still can't find it though.

**Comment by goggo24** [comment]
@AcademyPop in the formsetting from the activity you can choose the format for the questions sheet - we support DOCx, PDF and Latex ;)
![grafik](https://user-images.githubusercontent.com/16721900/164773120-e722a359-6b85-434a-8fad-fe2c76f3c912.png)
@quochung2310 I can reproduce the bug with v.3.11.2 of our plugin and will enter it in our backlog.

**Comment by quochung2310** [comment]
Yes, thanks for your reply. I have installed new version of this plug-in on Moodle 4.0.1 and it worked as expected.
