### ISSUE TITLE
Student ID

### ISSUE THREAD

**Issue by ttlan59** [academic-moodle-cooperation/moodle-mod_offlinequiz#177]
Thanks a lot for that great plug-in I just used thru my university!
However I had to go over several student ID numbers (one class counts around 1000 students).
Indeed in France "0" goes after "9" (computer keyboard, smartphone, ...) and with the stress beginning with "0" is not very ergonomic for the students (several squares shifted)
I wish students could code their student ID thru
1
2
3
4
5
6
7
8
9
0
But my University told me, there is no way to go around.
Any suggestion?
Thanks a lot!

**Comment by univietw** [comment]
This is not possible at the moment
I also don't think we will implement it, since the answer sheet is not very adaptable with the current code. We want to implement a OCR feature which would cut the crossing completely but I don't know when this will come.
