### ISSUE TITLE
Invalid get_string() identifier: 'id' or component 'moodle' if you use 'id' for user identification.

### ISSUE THREAD

**Issue by OT-AndreyUskov** [academic-moodle-cooperation/moodle-mod_offlinequiz#181]
If you use 'id' for user identification, you get a warning/error in Offlinequiz results:

Invalid get_string() identifier: 'id' or component 'moodle'. Perhaps you are missing $string['id'] = ''; in lang/en/moodle.php?
- line 353 of /lib/classes/string_manager_standard.php: call to debugging()
- line 7411 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
- line 191 of /mod/offlinequiz/report/overview/report.php: call to get_string()
- line 115 of /mod/offlinequiz/report.php: call to offlinequiz_overview_report->display()

There is no such string in moodle component. Another string must be used in this case.

Steps to reproduce:
1. Go to /admin/settings.php?section=modsettingofflinequiz and set 'User identification' parameter to '[4]=id'
2. Go to the 'Results' tab of an instance of Offlinequiz activity module
3. See the warning/error (debug and output must be activated)
![offlinequiz_id](https://user-images.githubusercontent.com/80508040/183874255-107e15a5-2133-4128-9585-482b3994989c.png)
![offlinequiz_id_error](https://user-images.githubusercontent.com/80508040/183874247-299670ef-45d9-4388-933d-8a3362014102.png)

Moodle 3.9.15, Offlinequiz v3.9.1 (2020060801)

**Comment by goggo24** [comment]
The Bug still occurs under moodle 4.x.
```
Invalid get_string() identifier: 'id' or component 'moodle'. Perhaps you are missing $string['id'] = ''; in lang/en/moodle.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7414 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 193 of /mod/offlinequiz/report/overview/report.php: call to get_string()
line 114 of /mod/offlinequiz/report.php: call to offlinequiz_overview_report->display()
```

**Comment by mwreichel** [comment]
Fix is included in v.4.3.0.
