### ISSUE TITLE
Unit tests failed

### ISSUE THREAD

**Issue by annouarf** [academic-moodle-cooperation/moodle-mod_offlinequiz#182]
Hi,
I have the version MOODLE_311_STABLE of offlinequiz.

When I run the following command : **vendor/bin/phpunit --testsuite core_privacy_testsuite**
I get the following error : 

core_privacy\privacy\provider_test::test_metadata_provider with data set "mod_offlinequiz" ('mod_offlinequiz', 'mod_offlinequiz\privacy\provider')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'core'
+'mod'

after investigation, i found that the unit tests fail in the line 43 of the file /offlinequiz/classes/privacy/provider.php  
**$collection->link_subsystem('mod_quiz', 'privacy:metadata:mod_quiz');**
the problem is : we cannot use mod in link_subsystem.

When i comment this line, the unit tests success.

The question is : 
is this line necessary ? if yes, how can I resolve this problem.

**Comment by leblangi** [comment]
@juzi, any news on that ? Thanks !

**Comment by djarran** [comment]
Any update on this?

I'm getting another privacy provider unit test error in a Moodle 4.1 environment:

```
2) core_privacy\privacy\provider_test::test_all_providers_compliant with data set "offlinequiz_regrade" ('offlinequiz_regrade', 'offlinequiz_regrade\privacy\provider')
Failed asserting that false is true.

/var/www/site/privacy/tests/privacy/provider_test.php:179
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80
```

**Comment by mwreichel** [comment]
Hi,
thanks for reporting this and the reminder.
It was fixed some days ago and is part of the latest minor releases.
