### ISSUE TITLE
Answer sheet layout

### ISSUE THREAD

**Issue by ncal-4on** [academic-moodle-cooperation/moodle-mod_offlinequiz#183]
Hi there, 

Is it possible to adjust the answer sheet layout? I have an exam that has 100 questions and it creates a 2-page answer sheet. WE are looking to have just a one-page answer sheet. The 2nd page has answer spots for only 4 questions. All the questions are multiple choice. 

The answers sheet has the answers in groups of 8 where the distractors a, b, c, d are at the top of each group of 8. I attached the answer sheet for reference. We have seen one where there were 106 questions on one page using offlinequiz. 

Hoping for guidance on how to get adjust the page settings so we have only the one pager for 100 questions.

Thanks

[OQT1_Offline_OIT4_answer_form_A_20221115_154849.pdf](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/files/10016140/OQT1_Offline_OIT4_answer_form_A_20221115_154849.pdf)

**Comment by goggo24** [comment]
I'm sorry, it's not possible to customize the answersheet.
