### ISSUE TITLE
default pdf scanned answer sheet  won't get graded properly

### ISSUE THREAD

**Issue by mailnowgr** [academic-moodle-cooperation/moodle-mod_offlinequiz#184]
Hi to everybody.
Attached there is a scanned answer sheet with 58 mc questions that can't be graded right.
Actually only the first column is "read" right up to question 24.
The other two columns are "read" by offline quiz wrong.
The scrennshot shows that 30d is read as 30b.
The same goes for all the questions from 25 to 58.
It is as if there is a huge gap between 1st - 2nd and 2nd - 3rd column of squares.
Really cant find why this is happening.
Appreciate any answer
Mike 
![offline_problem1](https://user-images.githubusercontent.com/119516794/204839445-2ac5ce15-c177-4010-90f1-eeaede9b78d8.jpg)

**Comment by carlosrozas** [comment]
I had similar issues with PDF, but switched to JPG files and everything works fine.

**Comment by mailnowgr** [comment]
> I had similar issues with PDF, but switched to JPG files and everything works fine.

Well I didn't make it clear. 
The printed answer sheet is from the pdf file offline quiz provides. 
The scanned and attached above sheet to be graded is jpg...

**Comment by univietw** [comment]
It seems like the recognition of the edges didn't work quite well.
Please try to move the blue circles so the cross inside matches the one on the paper. Then it should work.

**Comment by mailnowgr** [comment]
> It seems like the recognition of the edges didn't work quite well. Please try to move the blue circles so the cross inside matches the one on the paper. Then it should work.

Νο, this didn't help. It was the first thing I've tried...
