### ISSUE TITLE
Question analysis failed:

### ISSUE THREAD

**Issue by franzvinzenz** [academic-moodle-cooperation/moodle-mod_offlinequiz#187]
if i try the "Question Analysis" on Moodle 4.1 i get an Error:
Default exception handler: Fehler: Class 'qbank_previewquestion\previewquestion_helper' not found Debug: 
Error code: generalexceptionmessage
* line 1447 of /mod/offlinequiz/locallib.php: Error thrown
* line 945 of /mod/offlinequiz/locallib.php: call to offlinequiz_question_preview_button()
* line 143 of /mod/offlinequiz/report/statistics/statistics_table.php: call to offlinequiz_question_action_icons()
* line 832 of /lib/tablelib.php: call to offlinequiz_statistics_table->col_actions()
* line 665 of /mod/offlinequiz/report/statistics/report.php: call to flexible_table->format_row()
* line 382 of /mod/offlinequiz/report/statistics/report.php: call to offlinequiz_statistics_report->output_offlinequiz_structure_analysis_table()
* line 115 of /mod/offlinequiz/report.php: call to offlinequiz_statistics_report->display()

Then i changed the Line 1447 in locallib.php; and it seems to work: (remove: "previewquestion_")
            \qbank_previewquestion\helper::question_preview_popup_params());

**Comment by goggo24** [comment]
Thanks for reporting. Which version do you use? Can you add as the debugg message.

**Comment by franzvinzenz** [comment]
There is no class 'qbank_previewquestion\previewquestion_helper
but i chaned it to 'qbank_previewquestion\helper

**Comment by franzvinzenz** [comment]
$plugin->version   = 2022062100;

**Comment by franzvinzenz** [comment]
Moodle tells me, there is no update available.

**Comment by franzvinzenz** [comment]
Sorry.
I have just, seen, that it is corrected in the akual git-repo.
Thanks.

**Comment by franzvinzenz** [comment]
Hallo Eva,

 

thanks for your Response.

I have just seen that there is a new Version out (in the repo), where it is fixed.

But my Moodle doesn’t list the Update (yet).

 

Regards

Franz
