### ISSUE TITLE
Identifier for correct answers

### ISSUE THREAD

**Issue by ncal-4on** [academic-moodle-cooperation/moodle-mod_offlinequiz#189]
Hi there, 

Is there a way to change the correct answer identifier from "x" to a shaded square? Also to change corrections from shaded squares to something else (x over the shaded square) or to just a blank space?

Please advise.

Thanks,
Nina

**Comment by goggo24** [comment]
Hey Nina, there's no way to change the behaviour of checked (x) and corrected (filled) answers. Eva

**Comment by ncal-4on** [comment]
Hi Eva,

Okay - thanks for getting back to me. 

We have other exams running at the same time that uses scantron. For scantron the instruction is to fill in the space entirely for the correct answer. We are worried that the conflicting instruction would create confusion and then cause errors for examinees writing the different exams. We are looking to see if there was someone who can program to edit this behaviour. If you have any advice to share or tips on how this can potentially be done, would appreciate to know of it. 

Thanks very much.
Nina
