### ISSUE TITLE
dmlreadexception after update to Moodle 3.11 from Moodle 3.9

### ISSUE THREAD

**Issue by aojusto** [academic-moodle-cooperation/moodle-mod_offlinequiz#190]
Moodle version: 3.11.12+
mod_offlinequiz: branch MOODLE_311_STABLE

Hi there,

With [Moodle 3.11 improvement](https://tracker.moodle.org/browse/MDL-71099) where user info fields moved to mdl_user_info_field entity if i use any user_info_field as useridentification i get the following error (image attached).

Thanks in advance.

![offline_quiz_error](https://user-images.githubusercontent.com/91667131/222148548-6e542f5d-238d-4c4c-bf30-b8637ea6c27a.png)

**Comment by mwreichel** [comment]
Hi @aojusto,
sorry for our late answer to your request.
For user identification you can use all standard fields of the user table. Would it be possible use any of those fields instead?

**Comment by goggo24** [comment]
We will not be making any changes here, so I am closing this issue. Currently the attributes of the user table are supported. If you can provide a PR, we would be happy to accept it.
