### ISSUE TITLE
Upload link addressing to createpdfs 

### ISSUE THREAD

**Issue by mglaredo** [academic-moodle-cooperation/moodle-mod_offlinequiz#193]
We're working on a new Moodle 4.1 platform and using this plugin:

- $plugin->version   = 2022111501;
- $plugin->requires  = 2022041900;
- $plugin->component = 'mod_offlinequiz';
- $plugin->maturity  = MATURITY_STABLE;
- $plugin->release   = "v4.0.1";

We found a menu link not built properly. The diff workaround is shared as contribution for newer versions. Thanks in advance

diff view.php_orig view.php
389c389
 older--> $url = new moodle_url('/mod/offlinequiz/participants.php', ['mode' => 'createpdfs', 'q' => $offlinequiz->id]);
 newer--> $url = new moodle_url('/mod/offlinequiz/participants.php', ['mode' => /*'createpdfs'*/'upload', 'q' => $offlinequiz->id]);

**Comment by goggo24** [comment]
Thanks for reporting. Fixed in newer versions already.
