### ISSUE TITLE
useridentification configuration

### ISSUE THREAD

**Issue by samuelcalegari** [academic-moodle-cooperation/moodle-mod_offlinequiz#194]
Hello !

i'm using shibboleth authentication
in moodle users, the username field  is equal to email user field
inumber field is not mapped on users creation / login (because idnumbers can be the same  between users coming from University A  and University B, etc.)

how can i configure useridentification in parameters ?

Can I use email in  useridentification  ?

thanks !

**Comment by goggo24** [comment]
Hey, 

the user identification has to be set to a formula describing how the user IDs can be retrieved from the digits marked by the students on the answer forms. A user identification formula a[7]=username means that the students mark a 7 digit number on the answer form. A concatenation of the letter 'a' and that number denotes the 'username' of the user in Moodle's 'user' table. A formula b[5]cd=idnumber means that the students mark a 5 digit number on the answer form. A concatenation of the letter 'b', the marked number, and the string 'cd' denotes the 'idnumber' of the user in Moodle's 'user' table. 

Do you have any user field with digits that can be taken therefore? It would work with email too, if the scheme is for every student the same and only digits are different and unique => a[7]@univie.ac.at=email

**Comment by samuelcalegari** [comment]
ok i've understood ;) thanks for your explanations !
thank u
