### ISSUE TITLE
Unable to change instructions in french

### ISSUE THREAD

**Issue by Hamza-Falih** [academic-moodle-cooperation/moodle-mod_offlinequiz#196]
Hello everyone,

I am a beginner moodle developer.

I am trying to change the text/string of the instructions for the french language, but I can't seem to succeed.

I tried creating a new folder in lang for the french traduction (lang/fr/offliquiz.php) as follows : 
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/34319005/8fcc9605-7638-4314-a4c7-33003441987f)

But it doesn't seem to change anything : the PDF files generated still have the old instructions !

I also modified the offlinequiz.php file for english and it seems to strangely work though.

Can anyone help me find the right way to change the instructions for french ?

Thanks in advance !

**Comment by goggo24** [comment]
Why don't you use the language customisation feature via browser? See https://docs.moodle.org/403/en/Language_customisation. This is really convenient for an admin ;)

If you modify a file directly in your local pack then you will have to purge Moodle caches afterwards. Caches are purged automatically when using the language customisation feature. Have you purged the cache? The lang/fr/offliquiz.php can be found under moodledata/...?

**Comment by Hamza-Falih** [comment]
Thank you for your answer @goggo24 !
As this is an old issue, I can't seem to remember if I solved it in the end or not ^^'
Since I moved on from it, I certainly must have found a solution or a turnaround.
Have a good day !
