### ISSUE TITLE
the answers are recognized as given even if empty

### ISSUE THREAD

**Issue by zichichi** [academic-moodle-cooperation/moodle-mod_offlinequiz#198]
Hello, I have a strange issue while correcting the tests. Many times, the system reads blank boxes as given answers. Let me show you an example. This happens more often when I correct the user ID because it was marked incorrectly.

<img width="850" alt="a" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/1170727/7fd983c5-b7a8-4ba7-85f2-e4d50c5fa301">

**Comment by carlosrozas** [comment]
The same happens to my always after a manual correction on the ID.

**Comment by avolt1** [comment]
I am also having the same problem.
In addition sometimes even the marked boxes are read as empty and empty boxes are read as insecure (scanned with 300dpi).
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/136809936/05f00c57-97a2-4c8d-adea-1731f81b89e7)

**Comment by univietw** [comment]
can you tell me what PHP version you use?

**Comment by carlosrozas** [comment]
> can you tell me what PHP version you use?

In my case I am using 7.4.33, just because is the default in the hosting.

**Comment by zichichi** [comment]
> can you tell me what PHP version you use?

php 8.0.28

**Comment by GPLMU** [comment]
Hello, we have the same problem, random recognition of the answers for each manual correction of the ID. On our two server, first on PHP 7.4.28, second on PHP 7.3.19-1

**Comment by mwreichel** [comment]
Hi,
sorry for coming back to you so late.
Thank you for further comments on this issue. We already tried to simulate this behaviour with our instances, but it worked.

Does this still happen with your current version of the plugin?

If so, please could you give us further feedback on that?
Which versions of the plugin, Moodle and PHP you are using now?
Which solution and file format you use for scanning the answer sheets?

Thank you in advance.

All the best,
Martin
