### ISSUE TITLE
file types not supported

### ISSUE THREAD

**Issue by AV-HOST** [academic-moodle-cooperation/moodle-mod_offlinequiz#199]
Hello,

I am having the problem where my .pdf and .tif files are not accepted although these types are named as accepted.
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/136809936/afe711d7-8b1b-42d5-92f7-8f3aa61cfccb)

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/136809936/3c2b5dc9-f245-4ad7-8675-b44e6c19bee2)

I read in other issues that .pdf file types are working, mine is marked as 'not supported' because it has 'image type'. I also tried with OCR but got the same result. Why is .pdf and .tif not working?

My answer form is scanned with 300dpi and I saved the same file as .pdf, .tif, .png, jpg, bmp. Both .png and .jpg are working fine. (I know that .bmp is not supported).

Now the weird behaivior:
If I import all 5 files via .zip archive, I get '4 answer forms have been added to the evaluation queue...'.
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/136809936/5c039fc2-2df1-4185-b239-790dadc5ed1d)
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/136809936/37ae0bf0-9cba-4034-94cd-604f780e1e62)

But now it shows that .bmp is not supported because it 'has image type' and I have 3 positive imports. How did I get 3 when only .png and .jpg are working when importing one-by-one? (Correction of the ID worked and I got result for all 3 imports)
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/136809936/830f7daa-3597-45bf-a4dc-99f525a4406a)
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/136809936/9a62d399-a6d8-42a2-a3c1-746d7d1a4dfb)

How do I find out which other file type (.pdf or .tif) got accepted and which got lost in the .zip import? Is it possible to add a field to the overview where you can always see the file name?

Working with PHP 7.4.28, Plugin version 3.11.4 (2021070804)

Thanks in advance.

**Comment by Nirnae** [comment]
I'm encountering the same issue, did you find a fix for it ?

**Comment by goggo24** [comment]
Sorry for coming back so late. Have you been able to solve it in the meantime? Have you tried to upload it one by one? Have you scanned it black-white? If you use a zip, you could use 4 different answer sheets and not the same answersheet 4 times - so you can find out which one is missing.
