### ISSUE TITLE
English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-mod_offlinequiz#2]
Hi,
Great plugin!
When I was translating it in AMOS I noticed some minor typos and some german words in the English strings.
I'd suggest to replace the current contents of some strings as follows:

$string['imagickwarning'] = 'Missing imagick: Ask your system administrator to install the image magick library and check the path to the convert binary in your TeX notation filter settings. You cannot import TIF files without image magick!';

$string['matrikel'] = 'student number';

$string['offlinequizwillopen'] = 'Offline-Test opens on {$a}';

$string['totalpointsx'] = 'Total of marks: {$a}';

And, in the 'Group Questions > Grades' tab page, could you please change the currently used [grade] variable (from Moodle core) to [markedoutof] (from question.php), so that the page will have 'Marked out of' instead of 'Grade', and be more similar to the page of the Moodle core Quiz ?

I think that these changes will make your great plugin easier to use in English and easier to translate.

Thanks in advance for your help

**Comment by juzi** [comment]
The above strings have been changed in AMOS. I'm closing this issue.

**Comment by germanvaleroelizondo** [comment]
Thanks :+1:

**Comment by germanvaleroelizondo** [comment]
Hi Juergen,
I just checked AMOS and it seems there is still one German language string remaining at $string['matrikel'] = 'Matrikelnummer'

Can you please change it to $string['matrikel'] = 'student number'

Thanks again for a very nice plugin and the recent improvements that help all Moodle translators to make it available in other languages :)

**Comment by mkemmerling** [comment]
Thanks for reporting the german string in $string['matrikel']. We will fix this.

**Comment by mkemmerling** [comment]
Has been fixed in the master and MOODLE_28_STABLE branches (as well as in the current version 2015103000 available via moodle.org).

**Comment by pauloangelo** [comment]
There are many other typos in english translation. Example below.

$string['selectdifferentgroup'] = 'Please select a dfferent group!';
$string['imagickwarning'] = 'Missing imagick: Ask your system administrator to install the imagemagick library and check the path to the convert binary in your TeX notation filter settings. You cannot improt TIF files without imagemagick!';
-$string['insertnumber'] = 'Please insert the correct identification number marked by the blue frame.';  // Line repeated
