### ISSUE TITLE
Logo streching issue

### ISSUE THREAD

**Issue by fwsl** [academic-moodle-cooperation/moodle-mod_offlinequiz#20]
Plugin settings page has info about the logo: `The maximum allowed size is 520x140 pixels`
Plugin stretches the logo to 520 if the width is less than that, eg. if the logo is 80x140, the it will be stretched to 520x910 and will overlap the ID Number section.

**Comment by univietw** [comment]
Thank you for your response.
I can confirm this bug, as the code just scales the width of the logo to 520 pixels, the height is completely ignored.
The expected solution would be, that the image should be scaled to the biggest size fitting into 520x140 pixels.
You can work around, if you just scale the logo to the max size with any image editing software to the width of 520 pixels manually.
I will try to fix this small problem in the near future, as this is a bug, which is easy to fix.

**Comment by univietw** [comment]
I have made a patch for your problem, you can apply it in your local mod/offlinequiz The patch will be  released officially in Version 3.2. Hope this fixes your Problem.
[patch-github-20.txt](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/files/469912/patch-github-20.txt)

**Comment by fwsl** [comment]
Thanks for the patch, I've tested it, and it works like a charm. 
There is one more thing, when no logo is selected, by default universität wien logo is used, by my undestanding, in this situation, there should be no logo in the answers form.

**Comment by kaspot** [comment]
Thanks for your feedback. Glad it works out for you. 
Concerning the new feature - I’ll forward it to our developer. Thanks.
