### ISSUE TITLE
You can NOT find a cheat sheet for the plugin on the AMC website 

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-mod_offlinequiz#202]
Currently the English documentation for this plugin is NOT easily available.

It used to be in https://academic-moodle-cooperation.org/en/module/offline-quiz/

**Comment by goggo24** [comment]
You are right - we are just redesigning our website. We started with the german pages and will continue with english over the summer. Beyond that we will switch from PDF instructions to web pages. Please be patient and curious :)

In the meantime here arte the direct links to our english instructions:
- http://academic-moodle-cooperation.org/fileadmin/user_upload/p_aec/Cheat_Sheets/Carry_out_offline_quizes-EN.pdf
- https://academic-moodle-cooperation.org/dokumentation/multimedia-tutorials-auf-youtube/create-online-quiz-en/

**Comment by dinism** [comment]
The second link says:
Wie es aussieht, können wir nicht finden, wonach du gesucht hast. Vielleicht hilft eine Suche weiter.

**Comment by goggo24** [comment]
Ahh, I'm sorry - i thought we have a multimedia tutorial too, but it's only for creating an online quiz and not an offlinequiz => https://www.youtube.com/watch?v=KPVkfG8FT_o - i will delete the sescond link in my first answer.
