### ISSUE TITLE
README.md issue

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-mod_offlinequiz#203]
In the README.md text there is a problem in the Documentation section, where it has:

'You can find a cheat sheet for the plugin on the [AMC website](http://www.academic-moodle-cooperation.org/en/module/offline-quiz/)'

That link does not work:
'It seems we can’t find what you’re looking for. Perhaps searching can help.'

Please fix. 
Thanks in advance.

**Comment by goggo24** [comment]
We are just redesigning our homepage. Therefore some links are not working anymore. In the meantime you can open the cheat sheets/videos directly. We are also currently updating them for 4.x. 

English:
- [Carry out offline quiz](]https://academic-moodle-cooperation.org/wp-content/uploads/2023/06/Carry_out_offline_quizes-EN.pdf)

German:
- [Offline-Tests durchführen](http://www.academic-moodle-cooperation.org/fileadmin/user_upload/p_aec/Cheat_Sheets/Offline-Tests_durchfuehren-DE.pdf) (AMC)
- [Offline-Test – Ergebnisse herunterladen und auswerten](http://www.academic-moodle-cooperation.org/fileadmin/user_upload/p_aec/Cheat_Sheets/Offline_Test_-_Ergebnisse_herunterladen_und_auswerten-DE.pdf) (AMC)
- [Videotutorial: Offline-Tests durchführen](http://www.academic-moodle-cooperation.org/dokumentation/multimedia-tutorials-auf-youtube/offline-tests-durchfuehren/) (AMC)

**Comment by goggo24** [comment]
We have just released 4.1.2/ v.4.2.0. Please note https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/220 before you update. Our documentation is now updated too - we have new english ones ;) See README or https://academic-moodle-cooperation.org/mod_offlinequiz/ (at the bottom of page).
