### ISSUE TITLE
User table field doesn't support numbers in the field name

### ISSUE THREAD

**Issue by mhughes2k** [academic-moodle-cooperation/moodle-mod_offlinequiz#204]
https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/blob/3a88ffcfdb19cbfb0c78be096ee336a98ba2f741/locallib.php#L62

If you wish to use a user table field that has a number in it, for instance "phone1" or "phone2" this regular expression prevents you from doing so.

**Comment by goggo24** [comment]
Sorry for our late answer. It will be included in our next version.

**Comment by mwreichel** [comment]
Feature is released with v.4.3.0.
