### ISSUE TITLE
Can't use an updated version of question in OQ

### ISSUE THREAD

**Issue by acamacho-unige** [academic-moodle-cooperation/moodle-mod_offlinequiz#205]
Hi,

Since Moodle 4 update, we have question versions.

When updating a question inside an Offline Quiz activity, it is not possible to use this question without removing it from the exam and adding it again.

When trying to switch question version, Moodle gives an error about an `id missing for question`

Do anyone have this issue too ?

Thanks 

![4](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/114589068/0228cfdb-2828-4f23-b823-bcb72a188c59)
![3](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/114589068/f26c944d-b1b9-4e22-86b0-cdbcf16cc360)

**Comment by univietw** [comment]
Which offlinequiz version and moodle version are you using?

**Comment by ndunand** [comment]
@univietw we have the same issue using Using mod_offlinequiz 20232023070701 on Moodle 4.2.3 2023042403

**Comment by acamacho-unige** [comment]
We have 2023070701 and Moodle 4.1.5+.

**Comment by univietw** [comment]
OK, I guess I already fixed it with the upcoming version 4.2 I pushed my develop branch to develop_402. 
I am working on backporting all the fixes to 4.1.
The 4.2 is pretty much tested, maybe has a bug that we didn't catch, but I guess it's probably better than the 4.1 version

**Comment by ndunand** [comment]
@univietw thanks for the `develop_402` preview. Testing it on a test Moodle instance.

Do you want/need any feedback ? I've noticed a small inconsistency when dealing with question versions.

**Comment by univietw** [comment]
sure, feedback is welcome. if its small I'll put in 4.2.0 otherwise 4.2.1

**Comment by ndunand** [comment]
thanks for your reply @univietw 

I created #216 to have a specific discussion topic about the develop_402 pre-release branch.

**Comment by goggo24** [comment]
Thanks for your feedback and testing - we have just released v.4.2.0 and v. 4.1.2. Please note https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/220 before you update!
