### ISSUE TITLE
Error in moodle with Oracle DB

### ISSUE THREAD

**Issue by jaume77** [academic-moodle-cooperation/moodle-mod_offlinequiz#211]
Hi,

In the Moodle of the Universitat Autonoma de Barcelona (UAB) we have detected a problem in version: 2023070701 of Offlinequiz, when it is used in a Moodle environment based on an Oracle database.

When accessing the main screen of the activity, an error (attached image) appears in the database query: ORA-00979: it is not a GROUP BY expression.

![offlinequiz](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/2485232/d103b92b-c10c-4ae6-9da4-1d3f40c1b056)

From what we have seen, the problem is found in the **view.php** file, in the query on **line 76**, when using as SELECT fields one more field than in the GROUP BY (the og.sumgrades field).

```
//Start getting Data
$status = [];
$sql = "SELECT og.id, og.groupnumber, count(ogq.id) questions, og.sumgrades
          FROM {offlinequiz_groups} og
     LEFT JOIN {offlinequiz_group_questions} ogq ON og.id = ogq.offlinegroupid
         WHERE og.offlinequizid = :offlinequizid
      GROUP BY og.groupnumber, og.id
      ORDER BY og.groupnumber";
$status['groups'] = $DB->get_records_sql($sql, ['offlinequizid' => $offlinequiz->id ]);
```

We have added this field to the GROUP BY and from what we observe, the error disappears.

```
//Start getting Data
$status = [];
$sql = "SELECT og.id, og.groupnumber, count(ogq.id) questions, og.sumgrades
          FROM {offlinequiz_groups} og
     LEFT JOIN {offlinequiz_group_questions} ogq ON og.id = ogq.offlinegroupid
         WHERE og.offlinequizid = :offlinequizid
      GROUP BY og.groupnumber, og.id, og.sumgrades
      ORDER BY og.groupnumber";
$status['groups'] = $DB->get_records_sql($sql, ['offlinequizid' => $offlinequiz->id ]);
```
If this solution is correct, could you take it into account for the following versions of the plugin?

Thank you so much!

Jaume R.

**Comment by goggo24** [comment]
Dear Jaume, thanks for reporting. We will have a look!

**Comment by univietw** [comment]
@jaume77 It seems you have a lot of users and questions in your test. Can you give me an insight how many? Just for me to test if it works.

**Comment by mwreichel** [comment]
Fix is included in v.4.3.0.
