### ISSUE TITLE
No PDF files do not seem to be processed

### ISSUE THREAD

**Issue by systems77** [academic-moodle-cooperation/moodle-mod_offlinequiz#212]
Hi

In Offline Quiz version 4.1.0 (2023070701) for Moodle 4.1, there seems to be an issue when the plugin tries to process PDF files.

The processing message is shown on UI but the PDF files do not seem processed.

**Comment by univietw** [comment]
did you set up the cronjob correctly?
See https://docs.moodle.org/403/en/Cron for more info

**Comment by systems77** [comment]
Hi, this issue was sorted out.
