### ISSUE TITLE
{$a} string in title when switching language

### ISSUE THREAD

**Issue by crnfpp** [academic-moodle-cooperation/moodle-mod_offlinequiz#214]
Hi,
when switching from english to italian we have a {$a} in a title.
I guess maybe a typo in translation or something like that.
Is there a way we can fix this?
Thanks!

Plugin Versions: both 4.0 and 4.1
Moodle version: 3.9 and 4.1

 
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/80053276/2fa0faed-2755-4f0e-8c58-ffa37066ab7a)

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/80053276/9f977b71-286b-4ac1-a4ad-eaf00ec2d89d)

**Comment by dinism** [comment]
It's a problem of translation in AMOS

In english the string "Questions" **STILL** translated to "Modifica quiz offline: {$a}" in italian. It suppose to be "Domande"

Try this page: https://lang.moodle.org/local/amos/credits.php#credits-language-it

**Comment by crnfpp** [comment]
I'll look into it, thanks!
