### ISSUE TITLE
answer forms pending evaluation

### ISSUE THREAD

**Issue by nibar** [academic-moodle-cooperation/moodle-mod_offlinequiz#22]
Congratulations for this excellent component! Its features seems to be very useful. Unfortunately I cannot proceed to automatic grading of answer forms. I upload the problem free but there is a message stating that the evaluation is pending. The cron job seems to be executed without problems. I run Moodle 3.1.2. I have experimented with Tif and PNG uploads. No success. Presence forms are uploaded and processed without problems.

**Comment by nibar** [comment]
It was an error with cron job. Fixed. Apologies.

**Comment by kaspot** [comment]
happy you could fix it.
