### ISSUE TITLE
< and > characters in answers with plain text break PDF output.

### ISSUE THREAD

**Issue by juacas** [academic-moodle-cooperation/moodle-mod_offlinequiz#221]
When an answer contains the '<' or '>' characters the answers are truncated in the questions' PDF.
TCPDF needs those characters to be escaped as &lt; and &gt;.
Probably other characters need to be escaped too.

A solution may be doing some processing if the text is not HTML formatted, in pdflib.php:452

```php
       // Issue #221: Moodle editor allow editing answers in PLAIN and Moodle format without escaping < and > characters.
        // If answer format is not HTML then escape HTML special characters because they can break TCPDF.

        if ($question->options->answers[$answer]->answerformat != FORMAT_HTML) {
            $answertext = s($answertext);
        }
```
Just before:
```php
      // Remove all HTML comments (typically from MS Office).
        $answertext = preg_replace("/<!--.*?--\s*>/ms", "", $answertext);
```

**Comment by juacas** [comment]
Preview in HTML:
<img width="192" alt="image" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/1656180/f5206e11-3dad-4480-842a-86f5c4d3a089">
Generated PDF:
<img width="216" alt="image" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/1656180/2dca53f4-c61e-4c83-93bb-a476cfcf0ac6">

**Comment by mwreichel** [comment]
Hi @juacas ,
thank you for your request. In general this behavour should not happen and we do tests with questions and answers with < and > for every release. We also retested it now and it didn't occured with our instances.
Maybe it is connected to the version of tcpdf or any other plugin.

Please could you send us more details on this bug, concerning the version of moodle, the offlinequiz plugin and the tcpdf.

Thank you in advance,
Martin

**Comment by juacas** [comment]
My specs are:

Development platform:
- PHP Version 8.0.28
- Moodle 4.1.1
- TCPDF: 6.5.0 (2022-08-12) (delivered by Moodle)

Test platform:

- PHP 8.0.28
- Moodle 4.1.6
- TCPDF: 6.5.0 (2022-08-12) (delivered by Moodle)

How to reproduce:

Scenario A:

1. Change editor to "Plain text" in user's preferences.
2. Edit a option in a multichoice question.
3. Change "Format type" to "Plain text" or "Automatic".
4. Remove any HTML markup and enter a text with a "<" character, i.e. "This < character breaks the text cell"
5. Back to "offlinequiz".
6. Ensure the new version of the question is selected.
7. Delete the forms.
8. Check in the Preview that the option is readable: "This < character breaks the text cell".
9. Generate the question form in PDF.
10. Check the text. It should be truncated: "This ".

Alternatively:

1. Open a SQL client.
2. Locate the answer in mdl_question_anwers.
3. Set the field answer to "This < character breaks the text cell" and answerformat to 0.
4. Proceed to point 5 in previous list.

This character "<" can't be entered by hand with the Moodle Editor because it escapes it as &lt; but the issue happens when the questions are imported from plain-text formats as GIFT.

Thanks for this project and your efforts.

**Comment by mwreichel** [comment]
Thank you for your further information.
We will have a closer look on that.

**Comment by mwreichel** [comment]
Hi,
now we were able to observe this bug. I put the issue into our backlog to fix it.

**Comment by juacas** [comment]
The fix:

   ```php
     // Issue #221: Moodle editor allow editing answers in PLAIN and Moodle format without escaping < and > characters.
        // If answer format is not HTML then escape HTML special characters because they can break TCPDF.
        if ($question->options->answers[$answer]->answerformat != FORMAT_HTML) {
            $answertext = s($answertext);
        }
```
Works for us.
This assumes that:

- A text tagged in HTML format comes from a trusted source that knows the content is HTML-encoded propertly.
- A text that is not tagged as HTML is assumed to not have HTML content and should have their entities escaped with Moodle standard function s().

If you could provide some use-cases that are broke by this fix, I could try a better fix.

We would rather contribute a good solution to the project than manage a local patch.
