### ISSUE TITLE
error line 155 index.php

### ISSUE THREAD

**Issue by a-marti** [academic-moodle-cooperation/moodle-mod_offlinequiz#222]
I think we found an error. On the course block Activities, when we enter on Offline Quizzes, if on the course are quizzes on different sections, then a php error appear: null data property.
Checking the error line, 155 on index.php, we can see this code:
`if ($currentsection) {
    $learningtable->data[] = 'hr';
}`
I think this part of code is obsolete because the variable $learningtable doesn't appear anywhere else.

Testing, I think that is enough to delete this part of code, line 154, 155 and 156 of index.php, on the root of the mod.

**Comment by lposmb** [comment]
Hi,
We hit this problem also. `$learningtable` isn't declared nor used anywhere except index.php:155 at least for offlinequizz version 2023070702. It's seems to be similar to an html_table like in forum module.

Commenting out the if () arround line 155 restore the ability to have a result when going from the course page to "Activities / Offline Quizzes" (https://fqdn.tld/mod/offlinequiz/index.php?id=NNN)

**Comment by mwreichel** [comment]
Fix is included in v.4.3.0.
