### ISSUE TITLE
Updating a question doesn't update the Marks or Grade

### ISSUE THREAD

**Issue by Benjamin-unige** [academic-moodle-cooperation/moodle-mod_offlinequiz#225]
Moodle 4.2.3+ (Build: 20231201)
Offlinequiz v4.2.0 (2023113000)

When updating a question after a scan has been submitted the grade or marks are not updated properly

Steps to reproduce:
- create a new offlinequiz
- add a question "multiple choice" (one answer only), choice 1 grade 100%, choice 2 to 4 grade none
- answer the quiz correctly and upload the results
- in the review of result you should have "Mark 1.00/1.00 (100.00%)" and "Grade: 100.00 out of a maximum of 100.00"
- edit the question of the quiz to have choice 1 grade none and choice 2 grade 100%, save changes
- in the review of result the detail of the question is properly updated but grade and mark are unchanged

If you edit the question again without modifying it, just edit and save changes then the grade and marks are updated which makes me think that the update of these fields is happening before the calculation of the new version of the modified question.

**Comment by mwreichel** [comment]
Hi @Benjamin-unige ,
sorry for our late answer to that bug.
We already implemented a fix for Moodle 4.2.x (Offlinequiz v4.2.2).

Please could you check whether it works now as excpected.

Thanks,
Martin
