### ISSUE TITLE
Question PDF not properly generated when element has CSS font-size

### ISSUE THREAD

**Issue by JokaJukka** [academic-moodle-cooperation/moodle-mod_offlinequiz#232]
Hey there!
One of our teachers noticed a strange behaviour while generating question PDFs for his test.

For some reason (I would guess this is a fault of Moodle WYSIWYG editor), the text of one of the answers looked like this:
```html
<p dir="ltr" style="text-align: left;">The time d<span style="font-size: 1rem;">istribution of activities/tasks in the project cannot be clearly displayed in the Pert diagram.</span></p>
```

That "style" property probably caused a rendering error, as the resulted PDF looked something like this:
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/48550439/e5226d5f-48e7-4a7e-8f9b-93973a7f9e54)

I know this is somewhat of an edge-case, but would it be possible to handle this? I think that changing font size should not break the rendering.

**Comment by mwreichel** [comment]
Hi @JokaJukka,
sorry for our late answer to your issue.
In this case we can't provide any bugfix, it only could be "fixed" easily by the user itself.

All the best,
Martin
