### ISSUE TITLE
Statistics Report different between all-questions and one-question

### ISSUE THREAD

**Issue by acamacho-unige** [academic-moodle-cooperation/moodle-mod_offlinequiz#236]
Hello guys,

After doing some Offline Quiz exams, we saw that Statistics Report.
In this example question, a good answer is A.

On the question page, this is shown correctly with 100% and green color.
On all questions page, this is not showed for some questions. For those questions, the system does not say which reply is correct.

- **Question and answer analysis - All questions**

<img width="1557" alt="questionlist" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/114589068/29357f68-6940-4c38-b8c4-75f27f0c6bbc">

- **Question and answer analysis - One question**

<img width="1413" alt="onequestion" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/114589068/36b70012-1fcb-4c05-baed-287aa2276c66">

Some questions even give wrong statistics. In single page we see the right answer, and on the questions list page we see that all options are -25% (when one of them is clearly correct, and should show +100%)

<img width="1234" alt="2" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/114589068/f31590c6-b323-4445-a2f4-0c461394f487">

<img width="1165" alt="1" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/114589068/5b91d148-6b1f-43bd-8b03-db4420d28c6b">

Let me know if you have any information about that.

Thanks a lot

**Comment by mwreichel** [comment]
Hi @acamacho-unige ,
thanks for reporting this - sorry for our late answer.
We fixed this bug with the latest version of the plugin (v4.3.1).
