### ISSUE TITLE
Rendering source-code with highligted syntax in the quiz forms

### ISSUE THREAD

**Issue by dipanjanchakraborty** [academic-moodle-cooperation/moodle-mod_offlinequiz#239]
I am creating an offline quiz for a programming course. The questions and the answer options might have code snippets (in Java). I can use the option in the moodle question creation interface to highlight the syntax of the source code, and this renders fine on the moodle interface.

However, when generating the PDF forms for the quiz, all the lines in the code are rendered in one single continuous lines (the newlines in the "pre" environment are ignored). 

Is there any work around for this?

**Comment by obook** [comment]
Hello.
This bug is for all code snippets, without highlight filter also. I thing the problem is "pre" tag is removed, "code" tag is preserved.

Actual bug :
![Capture d’écran 2024-03-06 144434](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/460632/d17efb36-4401-495c-9992-07b5b1465e6d)

Expected :
![Capture d’écran 2024-03-06 144402](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/460632/5630a55a-0ca4-4855-b998-409588c2ea4b)

Actually, I try to find in source code where "pre" is removed.
This bug is seriously problematic for computer science assessments.

Olivier

**Comment by obook** [comment]
Is maybe a problem with ATTO html editor.
I actually make tests with TinyMCE HTML editor.

Regards.

**Comment by obook** [comment]
@dipanjanchakraborty : no problem with TinyMCE HTML editor...

**Comment by dipanjanchakraborty** [comment]
@obook same outcome even with TinyMCE HTML editor

Preview is fine:
![Screenshot from 2024-03-07 10-40-10](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/44966591/efb0da23-9453-470f-9d30-4757eadbd8d6)

But the PDF form is not:
![Screenshot from 2024-03-07 10-40-44](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/44966591/7d50184d-d5d7-4ebf-9e9a-38ce7e4adb0d)

This is the xml for the question:
```
<!-- question: 8  -->
  <question type="multichoice">
    <name>
      <text>Question 7</text>
    </name>
    <questiontext format="html">
      <text><![CDATA[<p>Consider the code below:</p>
<pre class="language-java"><code>class Voop {
     public static void main(String[] args) {
          doStuff(1);
          doStuff(1, 2);
     }
     // insert code here
}</code></pre>
<p>Which of the following line(s) if inserted in line 6 above will compile?</p>]]></text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.3333333</penalty>
    <hidden>0</hidden>
    <idnumber></idnumber>
    <single>false</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <showstandardinstruction>0</showstandardinstruction>
    <correctfeedback format="html">
      <text><![CDATA[<p>Your answer is correct.</p>]]></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text><![CDATA[<p>Your answer is partially correct.</p>]]></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text><![CDATA[<p>Your answer is incorrect.</p>]]></text>
    </incorrectfeedback>
    <shownumcorrect/>
    <answer fraction="50" format="html">
      <text><![CDATA[<p>static void doStuff(int... doArgs) { }</p>]]></text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="-50" format="html">
      <text><![CDATA[<p>static void doStuff(int[] doArgs) { }</p>]]></text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="50" format="html">
      <text><![CDATA[<p>static void doStuff(int x, int... doArgs) { }</p>]]></text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="-50" format="html">
      <text><![CDATA[<p>static void doStuff(int... doArgs, int y) { }</p>]]></text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>
```

**Comment by obook** [comment]
I make my question via https://smb33.keosystems.com/qcm/
Is GIFT format only (not XML), imported in question library, and run great in PDF.

**Comment by cmichale** [comment]
To Whom It May Concern,
 
 I am out of office until 11 Mar 2024.

In the meantime please contact
- for questions concerning e-learning including BOKUlearn: ***@***.***
- for questions concerning didactics in higher education: ***@***.***

Best regards,
Claus Rainer Michalek

>>> obook ***@***.***> 7.3.24 17:00 >>>

I make my question via https://smb33.keosystems.com/qcm/
Is GIFT format only (not XML), imported in question library, and run great in PDF.

**Comment by LisaE14** [comment]
Guten Tag,

ich bin bis einschließlich 11. März 2024 nicht im Büro.
In dringenden Fällen wenden Sie sich bitte an meine Kolleg*innen unter der DW 1111 oder per E-Mail an ***@***.***

Mit freundlichen Grüßen
Lisa Eckerstorfer

>>> obook ***@***.***> 03/07/24 17:00 >>>

I make my question via https://smb33.keosystems.com/qcm/
Is GIFT format only (not XML), imported in question library, and run great in PDF.

**Comment by obook** [comment]
> I am creating an offline quiz for a programming course. The questions and the answer options might have code snippets (in Java). I can use the option in the moodle question creation interface to highlight the syntax of the source code, and this renders fine on the moodle interface.
> 
> However, when generating the PDF forms for the quiz, all the lines in the code are rendered in one single continuous lines (the newlines in the "pre" environment are ignored).
> 
> Is there any work around for this?

A PDF make with (GIFT) tool https://smb33.keosystems.com/qcm/

![Copie d'écran_20240308_220213](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/460632/b6e8fa4e-48db-4a63-bcff-25d8bc8b2790)
