### ISSUE TITLE
Multiple Quiz Sheets - not recognized.

### ISSUE THREAD

**Issue by tomaprice** [academic-moodle-cooperation/moodle-mod_offlinequiz#24]
Hi,
We use Moodle 3.0 and I've installed your plugin but it's impossible to use a Quiz with several pages. When I upload the zip file, only the first page is recognized. The remaining pages are considered as copies of the first. I think there is a problem with the barcode on the bottom right.
I've talked about this problem with a colleague from another university. They upgrade their Moodle installation from 2.7 to 2.9 and now they have the same problem.
If you could have a look please.
Best regards.

**Comment by univietw** [comment]
We are already working on a hot fix for this. there is a problem in the database, how many pages the group has. You can fix this by changing the column numberofpages in the offlinequiz_groups table for every group you have a problem with, which is a bit annoying.
I will come to you later, when I have more Info.

**Comment by tomaprice** [comment]
Ok thank you!

**Comment by univietw** [comment]
The hotfix is completed and is tested right now. We had to make an update-script because the data in the database is wrong, so it took longer than expected.
There will be a hotfix-patch for the stable versions for 2.9, 3.0, 3.1 in the very near future.

**Comment by tomaprice** [comment]
Great! Thanks for you reply! 

---------------------------------- 
Thomas MAISONS 
Ingénieur TICE / Correspondant C2i 
---------------------------------- 
DSIUN - Université de Toulon - UTLN 
Bât.T - Bureau 107 
CS 60584 - 83041 TOULON CEDEX 9 
Tél. : 04 94 14 26 18 
http://www.univ-tln.fr 

Comme l'Université de Toulon, contribuez au respect de l'environnement en n'imprimant ce mail qu'en cas de nécessité. 


De: "univietw" <notifications@github.com> 
À: "academic-moodle-cooperation/moodle-mod_offlinequiz" <moodle-mod_offlinequiz@noreply.github.com> 
Cc: "tomaprice" <tmaisons@univ-tln.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 21 Octobre 2016 12:20:37 
Objet: Re: [academic-moodle-cooperation/moodle-mod_offlinequiz] Multiple Quiz Sheets - not recognized. (#24) 



The hotfix is completed and is tested right now. We had to make an update-script because the data in the database is wrong, so it took longer than expected. 
There will be a hotfix-patch for the stable versions for 2.9, 3.0, 3.1 in the very near future.

**Comment by mkemmerling** [comment]
The bug is now fixed in the MOODLE_29_STABLE, MOODLE_30_STABLE, and MOODLE_31_STABLE branches. Corresponding bug fix releases are available on moodle.org.
