### ISSUE TITLE
Being able to define user identification per activity (overwriting default one)

### ISSUE THREAD

**Issue by foxlapinou** [academic-moodle-cooperation/moodle-mod_offlinequiz#240]
Hi,

Offline Quiz always use a user identification setting defined in the activity settings, for the whole Moodle platform. This is generally good.

But sometimes, for specific uses, it would be useful to be able to overwrite this setting to define another field to use, specific for this precise activity.

I think that, being something risked (to not define things well), this ability should be restricted with a specific capability. Perhaps this capability would not be activated for any role (or just manager ?). It would just allow admin to allow this ability, only for specific people or categories/courses.

Even with the capability activated, authorized people would see default value, and would be able to change it only after clicking a checkbox to activate the dedicated field (like when you want to activate end course date on course settings).

Hope something can be done for that.

**Comment by mwreichel** [comment]
Hi @foxlapinou, 
thanks for your feature-request. We don't have this case/requirement at our universites. Therefore we won't change it at the moment, because other features have higher priority.
