### ISSUE TITLE
ERROR: Excepción - Call to undefined function popen()

### ISSUE THREAD

**Issue by carlosrozas** [academic-moodle-cooperation/moodle-mod_offlinequiz#243]
Hi, I just install offline quiz v4.3.1 (2024012201) in my Moodle server 4.3.3, but when try to upload the answer sheets from my students get the following message:

Excepción - Call to undefined function popen()

Any clue where to start to look to fix this problem?

Thanks in advance for any help

Carlos Rozas,PhD
Assistant professor
Laboratory of Neuroscience
Biology Department
Faculty of Chemistry and Biology
University of Santiago
Alameda 3363, Santiago, Chile.

**Comment by carlosrozas** [comment]
Forgot to add my configuration: 
Moodle 4.3.3+ (Build: 20240326)
PHP: 8.0.30
mariadb (10.6.17-MariaDB-cll-lve)

**Comment by univietw** [comment]
Hi Carlos,

popen is a function to open another program from PHP. Offlinequiz uses it to open the image conversion program "convert" for black/white conversion and some other image manipulation.

it seems to me that your php 8 has a security measure enabled that forbids using other programs from php.
try to find the "disable_functions" directive in your php.ini of your php 8 installation and delete the "popen" command. after restarting the php server it should work.
Here is some info about the "disable_functions" directive https://www.php.net/manual/en/ini.core.php#ini.disable-functions
the command popen offlinequiz is using:
https://www.php.net/manual/en/function.popen.php
and the image manipulation tool convert 
https://linux.die.net/man/1/convert

**Comment by carlosrozas** [comment]
Thanks for you detailed and fast response. I am trying to fix the issue about PHP 8.0 according to your instructions with my hosting provider, because I use CPanel have a limited capacity to make modifications.  I will let you know if is working. Thanks a lot.

**Comment by carlosrozas** [comment]
After asking to my hosting provider, the problem seems more complicated. They have already blocked popen() for PHP 8.0 and 7.4 (I can choose in Cpanel which one to use) as you expected, but the funny thing is running Moodle 4.0, OfflineQuiz v4.0.1 (2022111501) and PHP 7.4 in the SAME server everything run fine ans smooth. Now I am out of clue what is going on.

**Comment by univietw** [comment]
Hi Carlos,
sorry for coming back to you so late. I have no idea how to help you further.
Just fyi: Moodle uses this program as well for the LaTeX server image conversion with the tex-filter. (the filter is called "TeX notation" in moodle)
I understand hosting providers that want to block this. You could execute any program on the server which is obviously not safe. But without it I am not able to execute the external program. I have no idea why it did work, maybe they have configured an exception for you?

Maybe you can ask for an exception, but other than that I don't see a way to do it without changing your provider.
