### ISSUE TITLE
Statistics Report - Question analysis items not calculated

### ISSUE THREAD

**Issue by nuria2c** [academic-moodle-cooperation/moodle-mod_offlinequiz#245]
In the Question analisys report, ther are some items that are not calculated:
 - Facility index
 - Standard desviation
 - Effective weight
 - Discrimation index
 
 
![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/5544480/ff8fd122-1378-47c7-9fb8-4f661b5d5333)

In the Quiz statistics this items are calculated correctly,

![image](https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/5544480/4b0cbca5-d2dc-4a73-97cd-757c277a1786)

Moodle 4.3.3+ (Build: 20240320) Boost Union theme
OfflineQuiz version v4.3.1 (2024012201)

**Comment by univietw** [comment]
hi @nuria2c
Thank your for your submission.
We already found the bug on our own and I fixed it already in our development branch. You can check it out in the master. Once it is tested we will release another version.
