### ISSUE TITLE
Questions assigned to Offline Quiz become "zombies" when course is deleted

### ISSUE THREAD

**Issue by frankkoch** [academic-moodle-cooperation/moodle-mod_offlinequiz#25]
There is a strange behaviour of Offline Quiz. I created a course and added questions to the questionbase. Next I assigned some of these questions to an Offline Quiz. With the deletion of the entire course questions become deleted as well, however, only the Offline Quiz assigned questions remain within Moodle. They show up in other courses of the same course category under "Questions saved from context Course: nameOfDeletedCourse". I tried to delete these questions manually but they just become greyed-out and keep on being visible and editable. In fact I cannot delete these questions at all.

I tried the same with an ordinary Moodle quiz. With the deletion of the course all quizzes and questions become deleted as well. I would expect the same from Offline Quiz, however, Offline Quiz doesn't seem to clean up the question base at time of deletion. Given the nature of exam questions this seems to be a severe security issue.

I'm working on Moodle 3.1.2. and hope that you can rebuilt this scenario.

**Comment by kaspot** [comment]
Sorry for coming back to you so late. We've added the issue to our board and will discuss the further process.

**Comment by goggo24** [comment]
Beacue it's an realy old issue with an outdated version and we didn't get any other feedback in this direction, I will close this issue. Also we have never observed this bug on our own AMC instances.
