### ISSUE TITLE
 New monologo activity icon for Moodle 4.4

### ISSUE THREAD

**Issue by monnardj** [academic-moodle-cooperation/moodle-mod_offlinequiz#251]
In Moodle 4.4, activity icons have been redesigned. They are still 24 x 24, but the content is smaller and doesn't fill the entire space. The icon for offline quiz should be modified accordingly.
<img width="208" alt="image" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/5880250/97d4f7a6-57f1-4444-b552-4a03a34dfbd9">

**Comment by cmichale** [comment]
To Whom It May Concern,
 
 I am out of office until 07 May 2024.

In the meantime please contact
- for questions concerning e-learning including BOKUlearn: ***@***.***
- for questions concerning didactics in higher education: ***@***.***

Best regards,
Claus Rainer Michalek

>>> monnardj ***@***.***> 2.5.24 12:28 >>>

In Moodle 4.4, activity icons have been redesigned. They are still 24 x 24, but the content is smaller and doesn't fill the entire space. The icon for offline quiz should be modified accordingly.
<img width="208" alt="image" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/5880250/97d4f7a6-57f1-4444-b552-4a03a34dfbd9">


-- 
Reply to this email directly or view it on GitHub:
https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/251

**Comment by mwreichel** [comment]
Hi @monnardj,
thank you for your issue.
We already designed a new version of the icon, which will be part of the next version of the plugin.

Martin

**Comment by univietw** [comment]
The new logo is included in the master and will be included in the 4.4 upcoming 4.4 release
