### ISSUE TITLE
Set default font size. Accessibility.

### ISSUE THREAD

**Issue by sollericos** [academic-moodle-cooperation/moodle-mod_offlinequiz#254]
Accessibility staff has asked me to set the default font size to 12, but there is no setting for this. Can it be included in the next release?
Thanks

**Comment by univietw** [comment]
hi  @sollericos Thanks a lot for your suggestion. Since this is a quick and easy feature I implemented it for the upcoming 4.4 version.

**Comment by univietw** [comment]
I added your feature for the master branch and it will be part of offlinequiz 4.4.0
