### ISSUE TITLE
broken Moodle 4.1.5 upgrade path

### ISSUE THREAD

**Issue by phager-at** [academic-moodle-cooperation/moodle-mod_offlinequiz#255]
Es scheint, als sei Upgrade-Code von der 4.2-Entwicklungslinie in den 4.1 Branch gerutscht.
Ein Upgrade auf Moodle 4.1.5 schlägt fehl, da dort in der upgrade.php die Versionsnummer bereits auf den Stand von 4.3.2 erhöht wird.

Siehe: https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/blob/v4.1.5/db/upgrade.php#L1605

**Comment by univietw** [comment]
Hi @phager-at
Danke für den Bugreport. Da habe ich wohl nicht nochmal genau hingeschaut beim cherry-picken. Ich habe das jetzt anders gelöst und die darüber liegenden Upgrade-Pfade behoben, um den Nutzern das upgraden zu vereinfachen.
Die Version wird noch diese Woche kommen.
Danke und LG
