### ISSUE TITLE
Moodle 4.1 Version Error in 4.1.6 Update Preventing Plugin Update

### ISSUE THREAD

**Issue by RicardoUIB** [academic-moodle-cooperation/moodle-mod_offlinequiz#258]
I've encountered a version error in the code following the latest update to version 4.1.6, which is preventing the update of the plugin. Below, I have provided a solution along with a patch.

offlinequiz/db/upgrade.php:1613

.
.
.
    if ($oldversion < 2024012203) {
        require_once($CFG->dirroot . '/mod/offlinequiz/db/upgradelib.php');
        $subquery = "SELECT qr.id AS rid
                          FROM {question_references} qr
                     LEFT JOIN {context} c ON qr.usingcontextid = c.id
                         WHERE qr.component = 'mod_offlinequiz'
                           AND c.id IS NULL";
        $DB->delete_records_subquery('question_references', 'id', 'rid', $subquery);
--        **upgrade_mod_savepoint(true, 2024012200, 'offlinequiz');**
++        **upgrade_mod_savepoint(true, 2024012203, 'offlinequiz');**
    }
    return true;
.
.
.
This issue has been replicated under multiple environments, and the proposed solution has been tested successfully. I am posting this in hopes that it will assist others facing the same problem and to seek potential improvements to the patch.

**Comment by univietw** [comment]
thank you for the report. I released a new version with your suggested changes
