### ISSUE TITLE
4.4 Incompatibility

### ISSUE THREAD

**Issue by bozdag-ismail** [academic-moodle-cooperation/moodle-mod_offlinequiz#260]
When clicking on questions the error is thrown:

Exception - Failed opening required '[dirroot]/question/category_class.php' (include_path='[dirroot]/lib/pear:.:/opt/alt/php83/usr/share/pear:/opt/alt/php83/usr/share/php:/usr/share/pear:/usr/share/php')

Debug info:
Error code: generalexceptionmessage

Stack trace:
line 49 of /mod/offlinequiz/edit.php: Error thrown

<img width="706" alt="image" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/103765624/566c55fa-e678-48af-85ee-8fcb2022c7c1">

<img width="721" alt="image" src="https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/assets/103765624/aa70c013-1eb0-4b8c-ac82-fd10777219e0">

**Comment by univietw** [comment]
hi @bozdag-ismail
Thank you for your contribution.
This bug is already fixed in the 4.4 development version, which is not released yet, because it needs to be tested in detail first. You can find it in the master branch in this repository.
If you want to fix it on your instance you can just delete line 49 in the edit.php.

**Comment by nuria2c** [comment]
Hi, we've just tried this solution in out TEST environment and it doesn't works. There is another error:

Fatal error: Declaration of mod_offlinequiz\question\bank\custom_view::preview_question_url($question) must be compatible with core_question\local\bank\view::preview_question_url() in /var/www/html/moodle4/mod/offlinequiz/classes/question/bank/custom_view.php on line 148

**Comment by univietw** [comment]
I pushed a new commit, that should fix the issue
