### ISSUE TITLE
exporting code problem

### ISSUE THREAD

**Issue by x-wx** [academic-moodle-cooperation/moodle-mod_offlinequiz#266]
Thank you for developing such a great plugin.
I use East Asian language more, in the process of question, when exporting PDF, there will be a messy code problem, anyone solution for this? Thanks.

**Comment by univietw** [comment]
hi @x-wx For the 4.4 version we added a feature to choose the font for the pdf. While the version is not published yet you can check it out in the master. I hope this fixes your issue.
Best regards
Thomas

**Comment by x-wx** [comment]
Thanks for the reply. I'll check it out. 
Also could the layout be a bit more free, in which case it would allow the exported question paper to be closer to the everyday question paper model.
Good luck. Thanks again.

**Comment by LisaE14** [comment]
Guten Tag,

ich bin bis einschließlich 23. Juni 2024 nicht im Büro.
In dringenden Fällen wenden Sie sich bitte an meine Kolleg*innen unter der DW 1111 oder per E-Mail an ***@***.***

Mit freundlichen Grüßen
Lisa Eckerstorfer

>>> x-wx ***@***.***> 06/19/24 03:16 >>>

Thanks for the reply. I'll check it out. 
Also could the layout be a bit more free, in which case it would allow the exported question paper to be closer to the everyday question paper model.
Good luck. Thanks again.

**Comment by cmichale** [comment]
To Whom It May Concern,
 
 I am out of office until 25 November 2024.

In the meantime please contact
- for questions concerning e-learning including BOKUlearn: ***@***.***
- for questions concerning didactics in higher education: ***@***.***

Best regards,
Claus Rainer Michalek

>>> "Martin W. Reichel" ***@***.***> 20.11.24 09:20 >>>

Closed #266 as completed.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/266#event-15363101629
