### ISSUE TITLE
Missing plugin regrade in 4.4.0

### ISSUE THREAD

**Issue by CartierPierre** [academic-moodle-cooperation/moodle-mod_offlinequiz#277]
Hi,  
My moodle instance says the plugin "regrade" from offline_quiz is missing.  
The plugin looks missing here : https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/tree/v4.4.0/report/regrade

It was here in previous version : https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/tree/v4.3.3/report/regrade

Is it normal ?
Thanks

**Comment by mwreichel** [comment]
Hi @CartierPierre,

thank you for your question.
This is true. With the version for 4.4, manual regrading was removed, because of automatic regrading by switching the version of a question.

All the best,
Martin
