### ISSUE TITLE
Export offlinequiz content equation 

### ISSUE THREAD

**Issue by alfdeveloper** [academic-moodle-cooperation/moodle-mod_offlinequiz#29]
I'm using your plugin on a real website, when I download pdf form I got this "Image file: /home/kythiquo/moodledata/temp/offlinequiz/14787846252806_71853.gif not found! " 
instead of my equation. When I run in localhost, It work! Please help me!

**Comment by univietw** [comment]
It seems like your texfilter isn't working. Have you installed imagemagic, have a working texfilter and is the convert into images working on your server?

**Comment by kaspot** [comment]
I will close this issue after there has been no coming back from the reporter.
