### ISSUE TITLE
Fatal error: Call to a member function is_extra_row() on a non-object in

### ISSUE THREAD

**Issue by Supper1990** [academic-moodle-cooperation/moodle-mod_offlinequiz#3]
Hello, I very want to use this mod for Moodle, but I can't.
When I install module, i can't to modify any questions. "Group Questions" doesn't work for me.

My moodle is 2.8.5. 

Fatal error: Call to a member function is_extra_row() on a non-object in /var/www/webapps/moodle/question/classes/bank/view.php on line 191 

I very want to find any solution for this error.

**Comment by jonwestfall** [comment]
Same Issue, Running Moodle 2.9

**Comment by juzi** [comment]
Dear Supper1990, dear jonwestfall, 

as you can see, our git repository does not contain branches for Moodle 2.8 onwards. 
A version of the offlinequiz_module for Moodle 2.8 is currently under development and will be stable until end of August 2015. 
If you are interested in an experimental build. Please e-mail me and I can send it to you.
Unfortunately, the management of the github repository is not under my control and our master branch is not up-to-date. 

Cheers 
 Juergen Zimmer

**Comment by kaspot** [comment]
the newest 2.8.5 version of this plugin is now available on github.
