### ISSUE TITLE
MCQ Breakdown

### ISSUE THREAD

**Issue by nibar** [academic-moodle-cooperation/moodle-mod_offlinequiz#31]
The plugin is excellent. I need to export in excel the breakdown of the results (i.e. a list with the answers of each candidate to each question). This is possible in online quiz and there is also a plugin but does not work with offline quiz. Any help would be strongly appreciated.

**Comment by goggo24** [comment]
It is possible to download the result in different formats (xlsx,...) even with different information (answers or/and points). I think for your purpose the format "textfile with points" could be a solution. You can find the download option directly in the offline quiz under table for the results - see screenshot. Does this help?

![text_with_points](https://cloud.githubusercontent.com/assets/16721900/22554963/60394bc8-e962-11e6-83c3-653a21e154a2.png)

**Comment by nibar** [comment]
Many thanks!!! That was exactly what I needed.

**Comment by goggo24** [comment]
Perfect! I will close the issue.
