### ISSUE TITLE
There is no indication whether a MC-question is "one answer only" or "multiple answers allowed".

### ISSUE THREAD

**Issue by frankkoch** [academic-moodle-cooperation/moodle-mod_offlinequiz#35]
Moodle distinguishes MC questions with "one answer only" and "multiple answers allowed". If MC-questions are answered within a Moodle Quiz, Moodle doesn't allow to mark a second answer in a question of type "one answer only". Moodle quiz also generates text for each MC-question indicating whether it is a one or many question. 

Unfortunately, this distinction isn't indicated on the question sheet in Offline Quiz. Of course, on paper one can mark any number of answers. However, there should be an indication whether one only or many answers should be marked, otherwise students in Offline Quiz have a big disadvantage compared to students taking a Moodle Quiz.

I reported this issue in https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/16 already and wonder why it became closed. The issue is still there.

**Comment by univietw** [comment]
Hi, there is a way to choose the way of what is displayed at the question sheets in the offlinequiz instance:
Form Settings ->Print info about answers you can choose between:
none
question type
number of correct answers

Is this what you are looking for?

**Comment by goggo24** [comment]
![all_nothing](https://cloud.githubusercontent.com/assets/16721900/24452741/f54b0060-1484-11e7-9543-8815610e8917.png)

**Comment by frankkoch** [comment]
Yes, that's what I was looking for. Thank you!
Maybe this shouldn't be an option but the default. However, good enough for me and you can close this issue again.
