### ISSUE TITLE
Cron + Latex

### ISSUE THREAD

**Issue by lbarosi** [academic-moodle-cooperation/moodle-mod_offlinequiz#36]
The plugin is awesome. I'm almost getting it to work swiftly (what is unfortunately that easy).
UBUNTU 16.04 + Apache2 + PHP7 + Moodle. 3.2.2 +  Offline quiz 3.2.1 (from moodle.org) + Minor fix in styles.css

I still have the following problems:
**1. Latex equations doesn't show in PDF. (apache log shows an error running dvips: "no such file") I'm using $$ delimiters and mathjax disabled and obviously it works file in screen preview mode.**

Using texdebug the images are created in moodledata/temp/latex, offlineQuiz creates the images in moodledata/filter/tex. The pdf generated has black blobs instead of the equation but they are linked to the correct text output (texexp).

**2. Importing the scanned images shows pending information forever. If I run moodle cron.php from the console the import succeds.**

**3. Opening the imported image for edition has no save button enabled, the operations works if I run moodlequiz cron from console)**

My crontab is
`*/1 * * * * /usr/bin/php  /var/www/html/moodle/admin/cli/cron.php >/dev/null
*/10 * * * * DATE=`date +\%Y\%m\%d`; /usr/bin/php /var/www/html/moodle/mod/offlinequiz/cron.php --cli=1 >> /var/log/moodle/cron-olq.log.$DATE 2>&1`

I am almost certain this is not a bug issue, but some tricky configuration which a user would really like some help.

thanks.

**Comment by univietw** [comment]
can you turn on the debug-logs and provide me the error messages? I would like to understand your problem first.

**Comment by univietw** [comment]
I will close this issue now, if you still have problems feel free to reopen it.
