### ISSUE TITLE
Fails for Wiris Editor 

### ISSUE THREAD

**Issue by ajinkyagadewar** [academic-moodle-cooperation/moodle-mod_offlinequiz#38]
Offline quiz is unable to render image for Math and Chemistry formulaes created using Wiris Plugin.

As of now it is rendering as:
 «math xmlns=¨http://www.w3.org/1998/Math/MathML¨ class=¨wrs_chemistry¨»«mn»4«/mn»«mo»§#8594;«/mo»«mn»3«/mn»«/math»

Wherein it should render as  5 -> 3

This gets rendered properly in Online Quiz of moodle.
Wiris Plugin URL: http://www.wiris.com/plugins/docs/moodle

**Comment by ajinkyagadewar** [comment]
Same is happening with TeX notation

**Comment by univietw** [comment]
Hi, we don't support anything other than Tex-formulas at the moment. It's not likely that this will change very soon. If you provide a patch, we would be happy to look into it.
