### ISSUE TITLE
Inline Answers

### ISSUE THREAD

**Issue by hsssystems** [academic-moodle-cooperation/moodle-mod_offlinequiz#39]
Hi, 

would it be possible to provide a single pdf with inline answers? That's easier to handle for students and stuff but for sure more difficult to scan. However, do you think such an approach would be possible? Have you ever thought about this?

br

Harald

**Comment by univietw** [comment]
I don't think inline answers are likely to happen.

I really would like to have this feature, but it's already complicated to evaluate the answer sheets without any special formatting. It would take a lot of effort to find out where the answer boxes are.
The next problem would be, that the students actually would have to write down their identification number on every question sheet as well, which is very error-prone.
Furthermore this would only work with PDF.
I think the value you get out of this feature is not worth the effort, sadly.
