### ISSUE TITLE
allow custom user profile fields for user identification

### ISSUE THREAD

**Issue by webers-technikum-wien** [academic-moodle-cooperation/moodle-mod_offlinequiz#43]
would it be possible, to allow custom user profile fields for user identification?

our main IDs are alphanumeric and thus not suited for this plugin. We added a secondary numerical identification as a custom user field to Moodle, however, if I want to configure our custom user field as user identification in the plugin settings, I get: "Invalid field of the user table used."

**Comment by univietw** [comment]
This is already requested with #30, it is on our roadmap already.
