### ISSUE TITLE
Add new question don't work with my theme (fordson)

### ISSUE THREAD

**Issue by kama-jo** [academic-moodle-cooperation/moodle-mod_offlinequiz#47]
Hello, 

When I'm on the interface for edit offline quiz and I want add a new question this option don't work with my theme (fordson). I have a error message "**You must select a question type**" but I can't select a question type. 
I tried with other theme and it works.

Do you know where this problem can come from ?

Thanks,
Jonathan.

**Comment by univietw** [comment]
which Version do you use?
There was a bug with the 3.2-version of this plugin, that did had exactly your problem boost based themes. If you are using the 3.2-Version please try to update to the current version 3.2.5.

**Comment by univietw** [comment]
Since this problem is fixed in all newest minor-versions, as far as I can see, I will close this issue. Feel free to reopen it, if you have any problems
