### ISSUE TITLE
Length of ID-number field

### ISSUE THREAD

**Issue by iamwretched** [academic-moodle-cooperation/moodle-mod_offlinequiz#51]
We are just starting to use this plugin. It is great. Congratulations!

We have an issue that we don't know how to deal with. Most of our users have 8-digit IDs in the Moodle user table. But some earlier ones have only 6 digits. If we set up the formula as a[8]=username, the 8-digit students are identified correctly but not the 6-digit ones (Error: User does not exist). 

Is there a workaround or are will we need to normalise the length of our ID-Number field data?

Any help appreciated.

**Comment by goggo24** [comment]
Sorry, for not answering. You havte to normalise them - the 6-digit will be interpreted as 00xxxxxx and that won't work.
