### ISSUE TITLE
Quiz report similar to moodle core

### ISSUE THREAD

**Issue by Andrewolico** [academic-moodle-cooperation/moodle-mod_offlinequiz#56]
Firstly, thank you to you and your team for the offline quiz plugin. It's really fantastic and so valuable. 

I am wondering if it is possible to list/export a cohort with a breakdown of the marks allocated to each individual question. Like what you get on the standard moodle quiz report. 

Willing to contribute to dev/support costs for this.

**Comment by univietw** [comment]
Hi,
I'm not 100% sure what you are looking for, but from what I see, the "question and answers" sub-tab in the tab statistics is what you are looking for?

Greetings
Thomas

**Comment by Andrewolico** [comment]
Hi Thomas,

Thanks so much for your response. We're looking for a list of students who have completed the quiz and then their marks on each question. Like so:

![quiz-report](https://user-images.githubusercontent.com/20690233/35498871-d16fb588-04d8-11e8-91d5-d90ce9060964.png)

**Comment by goggo24** [comment]
Hey ,
on the overview page of the results under the table you have the opportunity to download the results. If you choose "**Textfile with points**" - you get the points of everey question similar to the quiz, but only in a file. 
![download_results](https://user-images.githubusercontent.com/16721900/35499256-e9cf0496-04d1-11e8-8163-ed9f2a1c859c.png)

**Comment by Andrewolico** [comment]
Brilliant. I missed that. Thanks so much. Very happy now. :-)

**Comment by goggo24** [comment]
You are welcome. So, can we close the issue?

**Comment by univietw** [comment]
I will close this issue now, feel free to reopen it, if you have further questions
