### ISSUE TITLE
Missing version file

### ISSUE THREAD

**Issue by nitro2010** [academic-moodle-cooperation/moodle-mod_offlinequiz#6]
Warning: include(/warehouse/lampp/htdocs/moodle/mod/offlinequiz/report/regrade/version.php): failed to open stream: No such file or directory in /warehouse/lampp/htdocs/moodle/lib/classes/plugin_manager.php on line 294

Warning: include(): Failed opening '/warehouse/lampp/htdocs/moodle/mod/offlinequiz/report/regrade/version.php' for inclusion (include_path='/warehouse/lampp/htdocs/moodle/lib/zend:/warehouse/lampp/htdocs/moodle/lib/pear:.:/opt/lampp/lib/php') in /warehouse/lampp/htdocs/moodle/lib/classes/plugin_manager.php on line 294

Warning: include(/warehouse/lampp/htdocs/moodle/mod/offlinequiz/report/regrade/version.php): failed to open stream: No such file or directory in /warehouse/lampp/htdocs/moodle/lib/classes/component.php on line 1105

Warning: include(): Failed opening '/warehouse/lampp/htdocs/moodle/mod/offlinequiz/report/regrade/version.php' for inclusion (include_path='/warehouse/lampp/htdocs/moodle/lib/zend:/warehouse/lampp/htdocs/moodle/lib/pear:.:/opt/lampp/lib/php') in /warehouse/lampp/htdocs/moodle/lib/classes/component.php on line 1105

**Comment by kaspot** [comment]
Thanks for the feedback. Could you please send us more information: screenshot, URL of occurance, ...
Thanks.

**Comment by kaspot** [comment]
no further information so closing...
