### ISSUE TITLE
localization of tutorial

### ISSUE THREAD

**Issue by ndunand** [academic-moodle-cooperation/moodle-mod_offlinequiz#63]
Hi,

We wanted to translate the tutorial into French for our students, but couldn't find any relevant language strings in the mod_offlinequiz language pack.

I then found that these were located in the `/tutorial/<langcode>` subdirectory of the plugin.

For easier localization through AMOS, this would better be defined as standard language strings.

**Comment by univietw** [comment]
Hi,

you are absolutely right. This tutorial exists since ages and doesn't have any ways of localizing. We are currently working on removing the German artifacts in this plugin, so including more localized code with your pull request would be the wrong way. We will discuss this topic in our team and I will provide a way to localize the tutorial according to the moodle guidelines.

**Comment by ndunand** [comment]
Thanks! I'll adapt our French translation accordingly

**Comment by goggo24** [comment]
Only a shirt update: we currently put our development ressources in the complete revision of the evaluation algorithm and at the moment have no time, to change the localization of our tutorial, but the issue is in our backlog but with lower priority. Cheers, Eva.

**Comment by sammuelcp** [comment]
> Oi,
> 
> Queríamos traduzir o tutorial para o francês para nossos alunos, mas não conseguimos encontrar nenhuma string de idioma relevante no pacote de idiomas mod_offlinequiz.
> 
> Então descobri que eles estavam localizados no `/tutorial/<langcode>`subdiretório do plugin.
> 
> Para facilitar a localização por meio do AMOS, é melhor definir isso como strings de idioma padrão.

Hello people,

at this address  https://moodle.org/plugins/translations.php?plugin=mod_offlinequiz you are informed that the plugin is 83% translated into Portuguese.

I would like to know how to download this translation and apply the plugin. 

I am directly changing the file located in the folder:

C:\Users\DL\Desktop\Moodle  PMAC\server\moodle\mod\offlinequiz\lang\en\offlinequiz.php

I'm using google translator to translate

I have already done some translations, but now another problem has arisen, the words that contain an accent are being replaced by a "?".

![quizz-min-min](https://user-images.githubusercontent.com/32909047/100105482-6ce4a400-2e35-11eb-9092-2d48fce28afb.png)

How could I solve this?

**Comment by mwreichel** [comment]
Hi @ndunand / @sammuelcp 
thank you for your comments on the tutorial. For Moodle 4.4 we re-designed it and now it supports translation like any other part of the plugin. You can try it out already on the master.
We would be delighted, if you could add your translations for French and Portuguese in AMOS after publishing.

The issue will stay open until the new version is released.

Kind regards,
Martin
