### ISSUE TITLE
Very slow correction

### ISSUE THREAD

**Issue by Gmirandagonz** [academic-moodle-cooperation/moodle-mod_offlinequiz#65]
I'm testing Offline Quiz. My problem is that the process of correction of the quiz is very very slow.
Yesterday it took 24 hours to receive the confirmation email and be able to receive the results in the plugin in Moodle. It was only 5 files with 4 questions.

Any idea of the causes of this problem and how to avoid it?

Thanks in advance.
Gonzalo

**Comment by dinism** [comment]
For better (mean faster) results alter cron task:

* | * | * | * | * | php -q /moodle/mod/offlinequiz/cron.php --cli=1

**Comment by Gmirandagonz** [comment]
Thank you. I will try.

**Comment by Gmirandagonz** [comment]
Than you! It works ok now.
