### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-mod_offlinequiz#66]
Invalid get_string() identifier: 'offlinequizclosed' or component 'offlinequiz'. Perhaps you are missing $string['offlinequizclosed'] = ''; in mod/offlinequiz/lang/en/offlinequiz.php?

line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 7083 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 373 of /mod/offlinequiz/classes/structure.php: call to get_string()
line 305 of /mod/offlinequiz/classes/output/edit_renderer.php: call to mod_offlinequiz\structure->get_dates_summary()
line 160 of /mod/offlinequiz/classes/output/edit_renderer.php: call to mod_offlinequiz\output\edit_renderer->offlinequiz_information()
line 360 of /mod/offlinequiz/edit.php: call to mod_offlinequiz\output\edit_renderer->edit_grades_page()

Is this OK?
In lan file:
**$string['offlinequizclosed'] --> Missing
$string['offlinequizisclosed'] --> Exists**

Changed mod/offlinequiz/classes/structure.php line 373, **error GONE**
From
$dates[] = get_string('offlinequizclosed', 'offlinequiz', userdate($offlinequiz->timeclose));
To
$dates[] = get_string('offlinequizisclosed', 'offlinequiz', userdate($offlinequiz->timeclose));

**Comment by dinism** [comment]
v3.4.2
2018011602

**Comment by goggo24** [comment]
Already fixed from v.3.5.+. Thanks for reporting!
