### ISSUE TITLE
Tiff files are not accepted [help]

### ISSUE THREAD

**Issue by gingeryo** [academic-moodle-cooperation/moodle-mod_offlinequiz#67]
Hi everybody,

This is my first demand for help on GitHub, so hello community.
I am a newbie so maybe my problem has been solved, but I didn't find any trace of it. 
If I miss it don't hesitate to redirect me, thank you.

I am trying to use offlinequiz and I cannot charge Tiff images and I do not know why. It works with PNG images, but not with TIFF image.

I try .tif and .tiff there is no changes. (see below)

Thank you by advance for your help,
Best regards,
Stéphanie 

![image](https://user-images.githubusercontent.com/37401706/42044166-9654a166-7af8-11e8-8a49-69ce8b86ff27.png)

**Comment by univietw** [comment]
Hello Stephanie,
can you tell me which version of the plugin you use?

**Comment by gingeryo** [comment]
Hello, 
I am using the version 3.2.5

**Comment by univietw** [comment]
that's a really old version. Do you use the corresponding offlinequiz version in 3.2-Stable?

**Comment by univietw** [comment]
For clarity reasons I will close this bug, feel free to open it, if you still have problems

**Comment by qveys** [comment]
Hello,

I use the version v3.3.2 and i have the same problem.
How did you solve it?
