### ISSUE TITLE
Offline quiz (2015060902) for Moodle 2.8 does not open question bank for adding questions

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-mod_offlinequiz#7]
Hi,
I just downloaded your offline plugin (2015060902) for Moodle 2.8 in a clean Moodle 2.8.7 server and sadly, I can not add questions from the question bank when i click add ' from question bank' nothing happens.

![offline quiz edit offline quiz](https://cloud.githubusercontent.com/assets/2671923/9701635/5ad9bd8a-53f8-11e5-9bc0-e89ce32cfe5a.jpg)

Adding n random questions and adding a new question both work OK.

The Moodle 2.7 version of this plugin works OK in a 2.7 server with the same question bank.

**Comment by germanvaleroelizondo** [comment]
When debugging mode is set to DVELOPER, there are no error messagges shown.

**Comment by juzi** [comment]
Hi,
I was about to suggest you activate debug logging. Could you also please have a look at your web server's error.log?
If that doesn't lead to any more knowledge I can install a Moodle 2.8.7 and try to reproduce the problem locally.

**Comment by germanvaleroelizondo** [comment]
Hi,
I re-installed a new windows 2.8.7 local server, imported some multiple choice questions, added the offline quiz plugin and I can not add questions from the question bank.
Enclosed is the error.log file dump:
![offline quiz error messages 1](https://cloud.githubusercontent.com/assets/2671923/9719445/f83cfcf2-5549-11e5-9c72-ba9dc28b3e9b.png)

and the apache error log:
![offline quiz apache error log](https://cloud.githubusercontent.com/assets/2671923/9719452/0313ca52-554a-11e5-9358-e868b2803a8d.png)

And the php error log:
07-S[ep-2015 22:27:08 Australia/Perth] PHP Warning:  file_get_contents(C:\M\M287\server\moodle/theme/): failed to open stream: No such file or directory in C:\M\M287\server\moodle\install\css.php on line 41

[07-Sep-2015 22:27:14 Australia/Perth] PHP Warning:  file_get_contents(C:\M\M287\server\moodle/theme/): failed to open stream: No such file or directory in C:\M\M287\server\moodle\install\css.php on line 41

[07-Sep-2015 22:27:19 Australia/Perth] PHP Warning:  file_get_contents(C:\M\M287\server\moodle/theme/): failed to open stream: No such file or directory in C:\M\M287\server\moodle\install\css.php on line 41

[07-Sep-2015 22:27:39 Australia/Perth] PHP Warning:  file_get_contents(C:\M\M287\server\moodle/theme/): failed to open stream: No such file or directory in C:\M\M287\server\moodle\install\css.php on line 41

[07-Sep-2015 22:27:48 Australia/Perth] PHP Warning:  file_get_contents(C:\M\M287\server\moodle/theme/): failed to open stream: No such file or directory in C:\M\M287\server\moodle\install\css.php on line 41

[07-Sep-2015 22:27:53 Australia/Perth] PHP Warning:  file_get_contents(C:\M\M287\server\moodle/theme/): failed to open stream: No such file or directory in C:\M\M287\server\moodle\install\css.php on line 41

[07-Sep-2015 23:09:05 Australia/Perth] PHP Warning:  mkdir(): File exists in C:\M\M287\server\moodle\lib\setuplib.php on line 1392

[07-Sep-2015 23:09:31 Australia/Perth] PHP Notice:  Array to string conversion in C:\M\M287\server\moodle\lib\adminlib.php on line 2670

[07-Sep-2015 23:09:31 Australia/Perth] PHP Notice:  Array to string conversion in C:\M\M287\server\moodle\lib\adminlib.php on line 2679

[07-Sep-2015 23:09:31 Australia/Perth] PHP Notice:  Array to string conversion in C:\M\M287\server\moodle\lib\adminlib.php on line 2670

[07-Sep-2015 23:09:31 Australia/Perth] PHP Notice:  Array to string conversion in C:\M\M287\server\moodle\lib\adminlib.php on line 2679

[07-Sep-2015 23:09:31 Australia/Perth] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in C:\M\M287\server\moodle\lib\adminlib.php on line 3068

[07-Sep-2015 23:09:31 Australia/Perth] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in C:\M\M287\server\moodle\lib\adminlib.php on line 3068

[07-Sep-2015 23:09:31 Australia/Perth] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in C:\M\M287\server\moodle\lib\adminlib.php on line 3068

I would appreciatte if you could install a clean 2.8.7 local server and try for yourself. My local server has mexican spanish language pack, but that should not make a difference. I will try an English only later today.

**Comment by germanvaleroelizondo** [comment]
I installed a new 2.8.7 windows local server in English only and the problem persists :(
![offline quiz error messages english](https://cloud.githubusercontent.com/assets/2671923/9720922/dbd46564-5558-11e5-9312-75cf6c7d525c.png)

**Comment by juzi** [comment]
Dear German, 

I'm sorry, but I cannot reproduce your problem. I've just downloaded a fresh Moodle 2.8.7+ from moodle.org and installed it in my linux box. I've installed the offlinequiz module  MOODLE_28_STABLE and it opens the question bank view.

Sorry, but there is not much that I can do from here until I can reproduce your problem. 

Cheers 
 Juergen

**Comment by bbdev2** [comment]
Question bank also doesn't show on windows installation of moodle v2.8.7.

**Comment by bbdev2** [comment]
Scanned files with cyrillic names save with incorrect encoding on windows, resulting in garbage names that do not correspond to database entries.

**Comment by juzi** [comment]
Could you please check if the popup for "add question from question bank" shows in mod_quiz, i.e. in a normal Moodle quiz?

**Comment by bbdev2** [comment]
yes, it does show

**Comment by germanvaleroelizondo** [comment]
Hi Juergen,

The windows local moodle server install uses MySQL. The standard quiz does work OK and does show the question bank in the same course.

I suspect this might be a windows-server issue. I'll check in on Mac later and report back.

I've been using the plugin version hosted in the Moodle plugins database.

**Comment by germanvaleroelizondo** [comment]
Hi Juergen,

Can you get a windows machine and install a local Moodle 2.8 server from https://download.moodle.org/windows/ and check ?

If this were a windows-server issue it might explain why there are almost no reports of this issue (very few people would use a windows Moodle server for real life work; many Moodlers only use it for testing.

**Comment by germanvaleroelizondo** [comment]
Hi Juergen,
As of today I have tested in two Windows 7 / 64bits PCs with identical results.

I'll try it later today (I hope) on a couple PCs more, a new virtual Linux box and 2 Macs I can get from my department..

**Comment by germanvaleroelizondo** [comment]
Hi Juergen,

I just installed Moodle 2.8 for MAMP for a local Mac version Moodle 2.8.7+ (Build: 20150716) with offline plugin version 2015060902 	2015-06-16 and it does NOT open the Question bank, while the standard Moodle quiz does open the question bank. NO DEVELOPER error messages are shown :(

Can you get a Windows PC or a Mac to reproduce the issue ?

**Comment by juzi** [comment]
Hi,
I've just installed the following package 
https://download.moodle.org/download.php/windows/MoodleWindowsInstaller-latest-28.zip

in my Windows 7 Enterprise running in a VirtualBox virtual machine. 
The offlinequiz opens the question bank popup without problems.

**Comment by germanvaleroelizondo** [comment]
Hi Juergen,
I installed a new local windows server from https://download.moodle.org/download.php/windows/MoodleWindowsInstaller-latest-28.zip in a Windows 7 64 bit PC.

I installed the offline quiz version 2015060902 from the installing plugins menu.

I imported 12 real-life questions and the standard Moodle quiz does open the question bank for adding questions, but the offline quiz does not open the question bank.

Following is the full contents of the exported-imported questions file I am using:

<?xml version="1.0" encoding="UTF-8"?>
<quiz>

  <question type="category">
    <category>
        <text>$course$/TODO EL CURSO COMPLETO/02 Degeneraciones celulares y tisulares/Cambios celulares y tisulares</text>

    </category>
  </question>


  <question type="multichoice">
    <name>
      <text>El administrar vitamina E a ovejas y corderos con enfermedad del músculo blanco</text>
    </name>
    <questiontext format="html">
      <text>El administrar vitamina E a ovejas y corderos con enfermedad del músculo blanco</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>es un tratamiento y prevención que inactiva radicales libres</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>activará las caspasas que inducirán apoptosis de fibras musculares</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>puede agravar el cuadro al producir metahemoglobinemia</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>puede causar calcificación metastásica iatrogénica</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>el edema celular se presenta cuando</text>
    </name>
    <questiontext format="html">
      <text>La hinchazón o edema celular se presenta cuando ...</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>Se detiene la bomba de sodio por falta de ATP</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>Se agotan las apoproteínas transportadoras de lípidos</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>Se activan genes promotores de apoptosis</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>Se activan las CASPASAS dependientes de calcio</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>En corderos con enfermedad del músculo blanco</text>
    </name>
    <questiontext format="html">
      <text>En corderos con deficiencia de selenio, que presentan enfermedad del músculo blanco, encontramos necrosis hialina (de Zenker) en músculos estriados debido a que ...</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>falta glutatión peroxidasa</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>falta catalasa</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>falta mieloperoxidasa</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>faltan caspasas</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>En mamíferos domésticos encontramos necrosis caseosa en casos de tuberculosis y en casos de</text>
    </name>
    <questiontext format="html">
      <text>En mamíferos domésticos encontramos necrosis caseosa en casos de tuberculosis y en casos de</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>micosis</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>salmonelosis</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>colibacilosis</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>toxoplasmosis cerebral</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>En un cordero de cuatro días de edad</text>
    </name>
    <questiontext format="html">
      <text><![CDATA[En un cordero de cuatro días de edad que murió de inanición-exposición debido a que su madre no lo amamantó Usted espera encontrar como lesión diagnóstica ...<br /><div style="text-align: center;"></div>]]></text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>degeneración mucoide de la grasa perirenal y pericárdica</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>Depósito de cristales de uratos en membranas serosas</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>Depósito de amiloide en glomérulos renales</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>Calcificación metastásica en tejidos blandos</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>la caida del cordón umbilical en corderos</text>
    </name>
    <questiontext format="html">
      <text><![CDATA[<p>La caida del cordón umbilical en corderos es un ejemplo de ...</p>]]></text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>gangrena seca fisiológica</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>gangrena húmeda patológica</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>gangrena gaseosa iatrogénica</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>apoptosis patológica</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>La grasa del caballo debe su color característico a</text>
    </name>
    <questiontext format="html">
      <text>Si al realizar la necropsia de un caballo macho de cinco años que murió con diagnóstico clínico de cólico observamos que la grasa subcutánea tiene un color amarillo, podemos presumir que el color de la grasa se debe a que contiene ...</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>carotenos y xantinas</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>bilirrubina libre</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>lipofucsina</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>hemosiderina</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>la necrosis caseosa debe su nombre a</text>
    </name>
    <questiontext format="html">
      <text>La necrosis caseosa debe su nombre a ...</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>aspecto macroscópico similar al queso cottage</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>aspecto macroscópico similar al queso suizo</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>olor fuerte parecido al queso Limburger</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>aspecto microscópico parecido al queso Oaxaca</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>la uratosis es más común en las especies</text>
    </name>
    <questiontext format="html">
      <text>La uratosis es más común en las especies que ...</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>se reproducen por huevos con cáscara dura</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>que tienen una placenta verdadera</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>que tienen los testículos en un saco escrotal</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>que son ovovivíparos</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>Si en un lobo mexicano encontramos necrosis de la grasa</text>
    </name>
    <questiontext format="html">
      <text>Si en un lobo mexicano macho adulto encontrado muerto en un parque nacional de Tamaulipas observamos necrosis de la grasa pericárdica y fractura reciente no sanada del femur izquierdo, usted sospecharía que la necrosis grasa estuviera asociada con ...</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>la dificultad para caminar y alimentarse</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>endotoxinas de bacterias Gram negativas</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>isquemia del mesenterio</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>pancreatitis aguda</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>Si un perro ingiere grandes cantidades de un rodenticida a base de vitamina D</text>
    </name>
    <questiontext format="html">
      <text>Un perro con hipercalcemia y calcificación metastásica puede deberse a ...</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>toxicidad de vitamina D (rodenticida)</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>deficiencia de vitamina E y selenio</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>error congénito del metabolismo de porfirinas</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>toxicidad de nitritos y nitratos</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>


  <question type="multichoice">
    <name>
      <text>Una cola de lagartija que se separa del cuerpo</text>
    </name>
    <questiontext format="html">
      <text>Una cola de lagartija que se separa del cuerpo en una situación de peligro, de permanecer a temperatura ambiente experimentará ...</text>
    </questiontext>
    <generalfeedback format="html">
      <text></text>
    </generalfeedback>
    <defaultgrade>1.0000000</defaultgrade>
    <penalty>0.1000000</penalty>
    <hidden>0</hidden>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <answernumbering>abc</answernumbering>
    <correctfeedback format="html">
      <text></text>
    </correctfeedback>
    <partiallycorrectfeedback format="html">
      <text></text>
    </partiallycorrectfeedback>
    <incorrectfeedback format="html">
      <text></text>
    </incorrectfeedback>
    <answer fraction="100" format="moodle_auto_format">
      <text>autolisis</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>necrosis</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>apoptosis</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
    <answer fraction="0" format="moodle_auto_format">
      <text>muerte somática</text>
      <feedback format="html">
        <text></text>
      </feedback>
    </answer>
  </question>

</quiz>

**Comment by germanvaleroelizondo** [comment]
I am afraid all the code was stripped from the file :(

I'll try to send you later a standard Email with the attached question file, which I fear might be the cause.

I tried firefox, chromium and safari browsers with the same negative results.

**Comment by juzi** [comment]
I just looked at the source code on Github and saw that the files in 
yui/build
are not there. So it can't work.
Unfortunately, I'm not responsible for the upload on Github. I'll see that it gets fixed.

**Comment by germanvaleroelizondo** [comment]
Thanks Juergen,

Can you please check the file in the Moodle plugin database at https://moodle.org/plugins/pluginversions.php?plugin=mod_offlinequiz ?

currently mod_offlinequiz_moodle28_2015060902.zip 

Thanks.

**Comment by juzi** [comment]
The ZIP archieve also does not contain the directory. 
I'm also not responsible for the publishing on moodle.org.
Maybe I'm wrong but I think the build directory has to be there because Moodle loads the JS files from there. Also, in a Moodle Core GIT checkout  in 
mod/quiz/yui 
there is a build directory provided.

**Comment by germanvaleroelizondo** [comment]
Thanks Juergen.

If you need help in publishing a complete ZIP package in the Moodle plugins directory you can contact David Mudrak, who is a very helpful guy.

In the meantime maybe it would be a good idea to publish something about this issue at https://moodle.org/plugins/view/mod_offlinequiz for the people who are currrently experiencing problems with the new version of this extremely useful plugin, so that they know that the ZIP file is incomplete but it will be fixed soon..

**Comment by juzi** [comment]
The problem is not that I need help. WRT Moodle I work inside the AMC and I'm not the person responsible for publishing modules. Other people do that.
I know David and he reviews our Modules when they get published (maybe not well enough ;) )

Before I post a notice, I'd like you to try whether adding the build directory actually solves your problem with the question bank not opening.

**Comment by germanvaleroelizondo** [comment]
Hi Juergen,
I'd happily do it, but I will need help. I'm a veterinarian with 0 programming skills.

I am currently using a Linux machine for updating the Departmental Moodle quizzes and I will re-boot into Windows OS in a couple of hours and give it a try then,

I will use your build directory available at
https://www.dropbox.com/s/i8qu2t95j5gtu9s/build.zip?dl=0

I have removed the large useless post with the failed question bank contents :) as you told me.

**Comment by juzi** [comment]
you don't need any skills. Just unzip the file and put the build folder inside this folder:
   <path to your moodle>/mod/offlinequiz/yui/

hope that helps.

**Comment by germanvaleroelizondo** [comment]
I can confirm that adding the build directory available at
https://www.dropbox.com/s/i8qu2t95j5gtu9s/build.zip?dl=0 DOES FIX THE ISSUE AND NOW THE PLUGIN WORKS BEAUTIFULLY :)

**Comment by pauloangelo** [comment]
I'm having the same problem.
Using Moodle 2.9.2, PostgreSQL. No PHP error messages on server side, but I could see the JS error below in the JS console of Firefox.

> TypeError: M.mod_offlinequiz is undefined

I copied the build directory under  /mod/offlinequiz/yui/ , as suggested by @juzi , but it is still not running.

Any clue? I will continue to debug. 

Thx,

PA

**Comment by pauloangelo** [comment]
Now running!

I needed a control+shift+r  to clear the JS cache.

Thank you @juzi, @germanvaleroelizondo and @bbdev2  .

PA

**Comment by mkemmerling** [comment]
The _yui/build_ directory is now included in the master and MOODLE_28_STABLE branches (as well as in the downloadable ZIP file at moodle.org). No need to download it separately from Dropbox any more.

Sorry for the troubles caused by the missing directory.

**Comment by juzi** [comment]
Dear German and others, 
since I don't have your e-mail addresses, I inform you via this thread that we published a hotfix for a serious bug in the offlinequiz module for Moodle 2.8. The bug produced wrong evaluations of answer forms under certain circumstances. Please install the latest version either from Github or moodle.org.

best regards 
  Juergen Zimmer

**Comment by pauloangelo** [comment]
Hi @juzi 

I'm having this problem here. We need to recalculate the grades... I will test the new version. 

Thank you.
PA

**Comment by juzi** [comment]
Hi Paulo,

The problem might not be solved by recalculating the grades. 
Short background: 
When you look at the preview of the question forms in an offlinequiz, the module creates so called group templates, where the question order and the order of the answers is saved for each offline quiz group. The PDF question forms are subsequently created from these templates. When an answer form is uploaded, the appropriate template is used to create a student attempt. 
However, when, e.g., the question order is changed, the templates have to be deleted because they don't correspond to the new question order anymore.
The bug we fixed was due to the fact that the templates where sometimes not deleted when they should have been.
The problem is minor if you have both, shuffle questions and shuffle answers within questions , deactivated, because then you can easily create the order of the questions as they occur on the question forms and create the templates again. 
However, with shuffle answers and/or shuffle questions activated, it is difficult to create the exact templates again.
If you have the latter problem, please contact me and I can connect you to a colleague of mine. She has a word macro that lets you easily create multiple choice questions with a certain order of answers. The resulting multiple choice questions can then be imported in Moodle and the offline quiz the students where answering can be re-created. This course of action is advised if you already 
have an offline quiz with many (hundreds of) results. 

We are sorry for the inconvenience we created with this bug. I was introduced by the major changes we did to the question editing interface for Moodle 2.8.

cheers 
   Juergen

**Comment by pauloangelo** [comment]
Thank you!
