### ISSUE TITLE
Problem generation pdf with latex in offline

### ISSUE THREAD

**Issue by kama-jo** [academic-moodle-cooperation/moodle-mod_offlinequiz#70]
Hello,

When i write a mathematical formula in offlinequiz and i want generate a pdf with this formula i have an error.

![message_erreur_28082018](https://user-images.githubusercontent.com/15214327/44723432-4ad20f00-aad0-11e8-8dd4-b26d3b6946ac.jpg)

My config  latex : 
![parametres_latex_28082018](https://user-images.githubusercontent.com/15214327/44723485-6ccb9180-aad0-11e8-8262-985d209b65fc.jpg)

Php version : 7.0.27
Moodle version : 3.2.9
Offlinequiz version : 3.2.5

How can I solve this problem ?

Thanks

**Comment by goggo24** [comment]
Sorry, for the late reply. Does the error still occour? Did you try to update on a more recent version?
Our TEX settings looks similiar, the only difference is that we additionaly use  \usepackage{mhchem} and 
as output image the format GIF. It works fine for us.
