### ISSUE TITLE
Çankaya Şubesinde Öğrenci Hesabında Ödev Gözükmemesi

### ISSUE THREAD

**Issue by emrahdirek** [academic-moodle-cooperation/moodle-mod_offlinequiz#71]
![screenhunter 483](https://user-images.githubusercontent.com/34771540/45173231-34cef780-b210-11e8-870c-e97abce65a3d.jpg)

**Comment by univietw** [comment]
Hi. This doesn't seem to be a mod/offlinequiz bug, but a cms-Bug. please report this to the official moodle bug tracker https://tracker.moodle.org
