### ISSUE TITLE
Problem with quiz preview (missing translaction)

### ISSUE THREAD

**Issue by mojaedukacja** [academic-moodle-cooperation/moodle-mod_offlinequiz#77]
in createquiz.php
Replace this:                 print('questionpage '. $question->page . '\n');
to this:    echo get_string('questionpage', 'offlinequiz') . ' ' . $question->page;

and in lang en.php
add this: $string['questionpage'] = 'Page';

**Comment by goggo24** [comment]
Thanks for reporting! I added it to our backlog.

**Comment by goggo24** [comment]
Thanks! We integrated your pull request in our next minor release v.3.6.2+ - coming soon!
