### ISSUE TITLE
wrong encoding for scanned files

### ISSUE THREAD

**Issue by bbdev2** [academic-moodle-cooperation/moodle-mod_offlinequiz#8]
Scanned files with cyrillic names save with incorrect encoding on windows, resulting in garbage names that do not correspond to database entries.

**Comment by bbdev2** [comment]
see also correct.php  - 952 string

**Comment by juzi** [comment]
Dear bbdev2,
we are happy to help you with your problems, but could you please be a bit more elaborate with your issues?

From your description above I cannot understand what exactly your problem is.
Could you provide an example of database entries that do not corrrespond... to whatever you mentioned before?

**Comment by bbdev2** [comment]
database:
![2015-09-08 16_34_15-217 - 217 197 13 159 -](https://cloud.githubusercontent.com/assets/14178602/9736200/7fe5b7f8-5648-11e5-9dcb-2acce95948f8.png)

in directory:
![2015-09-08 16_35_49-217 - 217 197 13 159 -](https://cloud.githubusercontent.com/assets/14178602/9736214/987e7ffc-5648-11e5-98f0-aa862e967dca.png)

image not loaded:
![2015-09-08 16_36_59-offlinequiz for moodle 2 8](https://cloud.githubusercontent.com/assets/14178602/9736228/a4b19b2e-5648-11e5-8f30-e0a78c43986b.png)

**Comment by juzi** [comment]
We use the moodle core API function "unzip_file"  to unzip ZIP archieves when they are uploaded in the offlinequiz. So my guess is that the problem actually lies in the moodle core. 
Could you write a simple php script that just includes  lib/moodlelib.php and unzips your file? 
If you want I could only write you that file. Like this we could see if it really is a moodle core problem and file a bug report at tracker.moodle.org.

**Comment by bbdev2** [comment]
For english filenames all work fine. When char length more than 1 byte we have a problem.

The problem is that moodle saves files in the system encoding (filename is converted from utf8 to system encoding). The simplest solution - to do filename conversion from system encoding to utf8 in сorreсt.php on 952 string. 
```
echo '<img id="scannedimage" name="formimage" src="' . $CFG->wwwroot .
   "/pluginfile.php/$context->id/mod_offlinequiz/imagefiles/0/" .
   iconv("###system encoding###","UTF-8",$imagefile->get_filename()) .'" border="1" width="' . OQ_IMAGE_WIDTH .
   '" style="position:absolute; top:0px; left:0px; display: block;">';
```
Sorry for my english=/.

**Comment by juzi** [comment]
I'm sorry, but I haven't had much time to look at this issue recently.
I haven't found a way to determine the ###system encoding###
Do you have an idea how I can determine that?
