### ISSUE TITLE
Support for Moodle 3.5.x Question Tagging

### ISSUE THREAD

**Issue by wickedcopters** [academic-moodle-cooperation/moodle-mod_offlinequiz#80]
Hi,

We would love to be able to select Random Questions by Tag (as per https://docs.moodle.org/35/en/Building_Quiz#Quiz_question_tags ). This feature was released in Moodle 3.5.0. We have your latest version and running Moodle 3.5.2 - it appears not to be sorted?

YouTube: https://www.youtube.com/watch?v=xNmqiCYDBDk

Regards

**Comment by ceremy1** [comment]
+1

**Comment by dinism** [comment]
+1

**Comment by johnpap21** [comment]
+1 - this is definitely something we would love to have implemented.

**Comment by goggo24** [comment]
Thanks for reporting! We have put the feature wish to our backlog.

**Comment by goggo24** [comment]
Tagging included in v.3.7.0+ - coming soon!
