### ISSUE TITLE
Offlinequiz with Oracle

### ISSUE THREAD

**Issue by jaume77** [academic-moodle-cooperation/moodle-mod_offlinequiz#81]
Hi,

INFORMATION:
- mod_offlinequiz_moodle34_2018011602.zip
- Moodle 3.4.1
- Oracle 12c

We have 2 problems using the 'Offlinequiz' module in a "Moodle" environment on DB Oracle:

1 - When executing the cron of the module, the following error appears:

```
Answer sheet evaluation for the offlinequiz-plugin

Execute scheduled task: Answer sheet evaluation for the offlinequiz-plugin (mod_offlinequiz\task\page_evaluation_task)
... started 11:49:05. Current memory use 9.7MB.
... used 1 dbqueries
... used 0.011188983917236 seconds
Scheduled task failed: Answer sheet evaluation for the offlinequiz-plugin (mod_offlinequiz\task\page_evaluation_task),S'ha produït un error en llegir a la base de dades
Debug info:
ORA-00932: tipos de dato inconsistentes: se esperaba - se ha obtenido CLOB
SELECT COUNT(*)
                     FROM m_offlinequiz_queue
                    WHERE status = 'processing'
                      AND timestart > :o_expiretime
[array (
  'o_expiretime' => 1542192545,
)]
Backtrace:
* line 277 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->query_end()
* line 1180 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->query_end()
* line 1571 of /lib/dml/moodle_database.php: call to oci_native_moodle_database->get_records_sql()
* line 1110 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->get_record_sql()
* line 1644 of /lib/dml/moodle_database.php: call to oci_native_moodle_database->get_record_sql()
* line 1854 of /lib/dml/moodle_database.php: call to moodle_database->get_field_sql()
* line 52 of /mod/offlinequiz/cron.php: call to moodle_database->count_records_sql()
* line 40 of /mod/offlinequiz/classes/task/page_evaluation_task.php: call to offlinequiz_evaluation_cron()
* line 104 of /lib/cronlib.php: call to mod_offlinequiz\task\page_evaluation_task->execute()
* line 292 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 91 of /admin/tool/task/schedule_task.php: call to cron_run_single_task()
```

Moodle works with the following types of data, according to the DB used : [https://docs.moodle.org/dev/XMLDB_column_types](url)

2- The column name "number" can not be used in Oracle (reserved word), but in the module tables it is used in "offlinequiz_p_lists" and in "offlinequiz_groups", which produces errors.

```
Debug info: ORA-00936: falta una expresión
SELECT * FROM m_offlinequiz_groups WHERE offlinequizid = :o_offlinequizid AND number = :o_number
[array (
'o_offlinequizid' => 3,
'o_number' => 1,
)]
Error code: dmlreadexception
×Stack trace:
•	line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
•	line 277 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->query_end()
•	line 1180 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->query_end()
•	line 1571 of /lib/dml/moodle_database.php: call to oci_native_moodle_database->get_records_sql()
•	line 1110 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->get_record_sql()
•	line 1543 of /lib/dml/moodle_database.php: call to oci_native_moodle_database->get_record_sql()
•	line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
•	line 922 of /mod/offlinequiz/lib.php: call to moodle_database->get_record()
•	line 125 of /mod/offlinequiz/lib.php: call to offlinequiz_after_add_or_update()
•	line 124 of /course/modlib.php: call to offlinequiz_add_instance()
•	line 154 of /course/modedit.php: call to add_moduleinfo()
```

Thanks!

**Comment by goggo24** [comment]
Thanks for reporting! Sorry for the late reply. Nobody of our AMC partner uses Oracle and so the error didn't appear in our environments. I will talk with our developer and will come back hopefully timely with an answer and our decision. Cheers, Eva

**Comment by jaume77** [comment]
Hi Eva!
Here at the Autonomous University of Barcelona (UAB) we are very interested in being able to use this plugin, if you can solve these bugs.  :-)
Thanks!
Jaume .

**Comment by univietw** [comment]
Hola Jaume,
finalmente una ocasion para practicar mi espanol :)
Si no tengo un base de datos de Oracle voy a hacer un push en el branch "develop_37_oracle" para usted, y estaría muy agradecido si pudiese comprobar si los errores se han solucionado.

So I would be very happy if you try out the develop_37_oracle branch and give feedback if it worked. If so, we will include it in the upcoming 3.7 release after some detailed testing.
 
Muchas gracias
Thomas

**Comment by univietw** [comment]
lo siento que respondio muy tarde. los modificaciones son en el branch "develop_37_oracle" y en "master" tambien

**Comment by jaume77** [comment]
Gracias Thomas!

Lo instalamos en nuestro entorno de testeo.

Saludos
Jaume R.

**Comment by jaume77** [comment]
Hola Thomas!

Estamos haciendo pruebas, y la parte de Oracle, en principio funciona correctamente... 

Solo una pregunta : 

Existe un parámetro en la configuración del módulo (**keepfilesfordays**), que en principio define el número de dias que se mantienen los ficheros **.tiff** en el directorio temporal, pero en las pruebas realizadas, estos ficheros no se eliminan nunca.

Hemos definido **keepfilesfordays = 2** dias. 

Pasados 4 dias, continuan estando los ficheros en el directorio temporal.

El cron de Moodle esta funcionando correctamente, pero parece que no se llame a la función del módulo ( _/offlinequiz/lib.php --> offlinequiz_cron()_ ), que por lo que vemos es donde se encuentra el codigo que elimina los ficheros temporales.

Si opinas que esta incidencia es mejor tratarla en un nuevo tema (issue), dimelo, y lo abro.

Muchas gracias avanzadas.
Jaume R.

**Comment by univietw** [comment]
Tienes razon. Es un problema que no esta conectado con oracle. Si quiere, puede abrir otra tema. Voy a corrigir pronto, por que esta un error muy importante. No se por que no hay ningunas problemas hasta ahora.
Si no tiene problemas con este version: Puedo cerrar este tema?
muchas gracias.

**Comment by jaume77** [comment]
Ok Thomas,

Abro tema referente al cron de eliminación de ficheros temporales.

La parte de Oracle, con las pruebas realizadas, funciona correctamente.

Si quieres, puedes cerrar este tema.

Muchas gracias!

**Comment by goggo24** [comment]
Gracias - thanks for testing, Code will be included in v.3.7.0.
