### ISSUE TITLE
spinner loading

### ISSUE THREAD

**Issue by Arshad83** [academic-moodle-cooperation/moodle-mod_offlinequiz#82]
when ever we want to add question from question. popup will not display tags option but it showing spinner loading in moodle3.5.x
![image](https://user-images.githubusercontent.com/22912846/48901891-d7e0f600-ee7c-11e8-8243-27b32203a0d3.png)

**Comment by goggo24** [comment]
Thanks for reporting! I think it's a subsequent error because of missing support of question tagging (see https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/issues/80). 
We have put the feature wish to our backlog.

**Comment by goggo24** [comment]
Tagging will be included in v.3.7.0.+ - so the spinning wheel will disappear. v.3.7.0. coming soon!
