### ISSUE TITLE
Simultaneous tasks : upload and cron 

### ISSUE THREAD

**Issue by MathieuDomingo** [academic-moodle-cooperation/moodle-mod_offlinequiz#85]
Hello, I think there is a problem with the cron.php script.

When I'm uploading a zip with many tiff, it take some time to fill the database  (specifically mdl_offlinequiz_queue_data)
From time to time, the cron start before the mdl_offlinequiz_queue_data is filled with all rows off the zip.
This result that $jobdata doesn't contain all the data. When all value of $jobdata are read, the status in mdl_offlinequiz_queue is taked as finished while some row in mdl_offlinequiz_queue_data are still marked as new. 

To patch it easily, I actually had a 
` while($jobdata != NULL){    `  around the  ` foreach ($jobdata as $data) {`
and before the end of the while I check if there is some new values for jobdata 
```php
$jobdata = $DB->get_records_sql("
                    SELECT *
                      FROM {offlinequiz_queue_data}
                     WHERE queueid = :queueid
                       AND status = 'new'",
                    array('queueid' => $job->id));
```

This seems to work nicely.
BTW, I think a better solution should be to look directly for "new" rows in mdl_offlinequiz_queue_data instead of mdl_offlinequiz_queue (but this may need more work to do it)

**Comment by goggo24** [comment]
Thanks for reporting!  
We are already working on the issue, but we will take a little different approach from your solution and will define a new cron status "uploading". The queue is created in the status "uploading", as soon as all files are there, the status is changed to "new" and the job can find the queue and all data inside. 
The solution will be included in v.3.5.4+ - coming soon!

**Comment by MathieuDomingo** [comment]
It's look like it's gonna be an elegant solution, I like this idea :-)

(My "solution" is only an easy way to patch it for people having the same problem, it's not a good way to do it ;-) )
