### ISSUE TITLE
Table prefix

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-mod_offlinequiz#86]
I tested the version 3.6.0. I upgraded from version 3.5.3 and i got a database error.
My tables have a different prefix: **mdlvn_** NOT mdl
I found the problem.
In file \db\upgrade.php
Line 1427: FROM   mdl_offlinequiz_choices c1,
Line 1428: mdl_offlinequiz_choices c2
The name of tables made error "don't exist" because it have different prefix from mine.
The same is in file \report\rimport\resultsaver.php
Line 161: FROM   mdl_offlinequiz_choices c1,
Line 162: mdl_offlinequiz_choices c2 
I changed these 4 lines from mdl_offlinequiz_choices to mdlvn_offlinequiz_choices and it was OK.

**Comment by moodleulpgc** [comment]
Same here, table prefix should NOT be hardcoded in upgrade.php
$DB has a method get_prefix()

**Comment by mojaedukacja** [comment]
confirm

**Comment by goggo24** [comment]
Thanks for reporting. We will try to take a look as soon as possible.

**Comment by goggo24** [comment]
Fix will be included in v.3.6.1+ - coming soon!
