### ISSUE TITLE
wrong ms sql query

### ISSUE THREAD

**Issue by bbdev2** [academic-moodle-cooperation/moodle-mod_offlinequiz#9]
offlinequiz/report/statistics/report.php - 1034 string.

```SELECT
1,
COUNT(1) AS countrecs,
SUM(sumgrades) AS total
FROM mdl_offlinequiz_results offlinequiza 
WHERE offlinequiza.offlinequizid = '2' AND offlinequiza.status = N'complete' AND offlinequiza.sumgrades IS NOT NULL
GROUP BY 1
```

exception:
Each GROUP BY expression must contain at least one column that is not an outer reference.

**Comment by mkemmerling** [comment]
Hi,
we do not test our plugins with MS SQL server since we run Moodle on Linux servers only. But if you could provide a patch for the SQL statement, we would accept it if it still works with MySQL and PostgreSQL.

Regards,
Markus Kemmerling
