### ISSUE TITLE
Misread page number barcodes lead to DB error

### ISSUE THREAD

**Issue by inceddy** [academic-moodle-cooperation/moodle-mod_offlinequiz#91]
You should add an SMALLINT overflow protection at https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/blob/b852b24c7d048b0e0e6026bb08e0abdb34d9bd18/evallib.php#L154 because misread barcodes might lead to huge numbers resulting in an DB exception which then brakes the complete import queue ;)

E.g.
```php
        // Prevent SMALLINT overflow on misread barcode
        if ($scannedpage->pagenumber > 32760) {
            $scannedpage->pagenumber = null;
        }
```

**Comment by goggo24** [comment]
Thanks for reporting! We will include the fix in our next minor release v.3.6.2.+ - coming soon.
