### ISSUE TITLE
Duplicated styles with mod_quiz

### ISSUE THREAD

**Issue by moodleulpgc** [academic-moodle-cooperation/moodle-mod_offlinequiz#99]
Hi,
We have this module installed along standard mod_quiz and mod_studentquiz. 
There is substantial overlap in styles, css rules, defined in styles.css between mod_offlinequiz and mod_quiz.  When debugging a custom theme I've seen duplicated rules for many  #categoryquestions ...  rules

Those rules defined here will find targets in pages by mod_offlinequiz AND in addition in pages by mod_quiz and mod_studentquiz that are probably NOT intended.

Most probably the css rules already defined in mod_quiz shoul NOT be duplicated here if identical. If the rule must be different, a more restrictive selector 
#page-mod-offlinequiz-edit #categoryquestions
should be used to affect only the pages generated by mod_offlinequiz.

**Comment by goggo24** [comment]
Thanks for reporting. We will have a look and think about a solution.

**Comment by goggo24** [comment]
Bug fixed with v.3.9.0. - already published. Have fun!
